echo off
call ..\..\cleancfast.bat
..\..\..\bin\cfast LLNL_01 /V
..\..\..\bin\cfast LLNL_02 /V
..\..\..\bin\cfast LLNL_03 /V
..\..\..\bin\cfast LLNL_04 /V
..\..\..\bin\cfast LLNL_05 /V
..\..\..\bin\cfast LLNL_06 /V
..\..\..\bin\cfast LLNL_07 /V
..\..\..\bin\cfast LLNL_08 /V
..\..\..\bin\cfast LLNL_09 /V
..\..\..\bin\cfast LLNL_10 /V
..\..\..\bin\cfast LLNL_11 /V
..\..\..\bin\cfast LLNL_12 /V
..\..\..\bin\cfast LLNL_13 /V
..\..\..\bin\cfast LLNL_14 /V
..\..\..\bin\cfast LLNL_15 /V
..\..\..\bin\cfast LLNL_16 /V
..\..\..\bin\cfast LLNL_17 /V
..\..\..\bin\cfast LLNL_18 /V
..\..\..\bin\cfast LLNL_19 /V
..\..\..\bin\cfast LLNL_20 /V
..\..\..\bin\cfast LLNL_21 /V
..\..\..\bin\cfast LLNL_22 /V
..\..\..\bin\cfast LLNL_23 /V
..\..\..\bin\cfast LLNL_24 /V
..\..\..\bin\cfast LLNL_25 /V
..\..\..\bin\cfast LLNL_26 /V
..\..\..\bin\cfast LLNL_27 /V
..\..\..\bin\cfast LLNL_28 /V
..\..\..\bin\cfast LLNL_29 /V
..\..\..\bin\cfast LLNL_30 /V
..\..\..\bin\cfast LLNL_31 /V
..\..\..\bin\cfast LLNL_32 /V
..\..\..\bin\cfast LLNL_33 /V
..\..\..\bin\cfast LLNL_34 /V
..\..\..\bin\cfast LLNL_35 /V
..\..\..\bin\cfast LLNL_36 /V
..\..\..\bin\cfast LLNL_37 /V
..\..\..\bin\cfast LLNL_38 /V
..\..\..\bin\cfast LLNL_39 /V
..\..\..\bin\cfast LLNL_40 /V
..\..\..\bin\cfast LLNL_41 /V
..\..\..\bin\cfast LLNL_42 /V
..\..\..\bin\cfast LLNL_43 /V
..\..\..\bin\cfast LLNL_44 /V
..\..\..\bin\cfast LLNL_45 /V
..\..\..\bin\cfast LLNL_46 /V
..\..\..\bin\cfast LLNL_47 /V
..\..\..\bin\cfast LLNL_48 /V
..\..\..\bin\cfast LLNL_49 /V
..\..\..\bin\cfast LLNL_50 /V
..\..\..\bin\cfast LLNL_51 /V
..\..\..\bin\cfast LLNL_52 /V
..\..\..\bin\cfast LLNL_53 /V
..\..\..\bin\cfast LLNL_54 /V
..\..\..\bin\cfast LLNL_55 /V
..\..\..\bin\cfast LLNL_56 /V
..\..\..\bin\cfast LLNL_57 /V
..\..\..\bin\cfast LLNL_58 /V
..\..\..\bin\cfast LLNL_59 /V
..\..\..\bin\cfast LLNL_60 /V
..\..\..\bin\cfast LLNL_61 /V
..\..\..\bin\cfast LLNL_62 /V
..\..\..\bin\cfast LLNL_63 /V
..\..\..\bin\cfast LLNL_64 /V
..\..\..\VandV_Calcs\Release\VandV_Calcs.exe CFAST_Pressure_Correction_Inputs.csv
copy ..\..\pressures.csv LLNL_Ambient_pressures.csv /Y
