@echo off
del *_compartments.csv /s/q >nul 2>&1
del *_devices.csv /s/q >nul 2>&1
del *_masses.csv /s/q >nul 2>&1
del *_vents.csv /s/q >nul 2>&1
del *_walls.csv /s/q >nul 2>&1
del *_calculations.csv /s/q >nul 2>&1
del *_n.csv /s/q >nul 2>&1
del *_s.csv /s/q >nul 2>&1
del *_f.csv /s/q >nul 2>&1
del *_w.csv /s/q >nul 2>&1
del *_m.csv /s/q >nul 2>&1
del *_c.csv /s/q >nul 2>&1
del *_d.csv /s/q >nul 2>&1
del *_git.txt /s/q >nul 2>&1
del *_zone.csv /s/q >nul 2>&1
del *_resid.csv /s/q >nul 2>&1
del *_slab.csv /s/q >nul 2>&1
del *.out /s/q >nul 2>&1
del *.smv /s/q >nul 2>&1
del *.plt /s/q >nul 2>&1
del *.status /s/q >nul 2>&1
del *.log /s/q >nul 2>&1
del *.sf /s/q >nul 2>&1
del *_slice.info /s/q >nul 2>&1
del *.iso /s/q >nul 2>&1
del *.sinfo /s/q >nul 2>&1
del *.err /s/q >nul 2>&1
