module exit_routines

    use precision_parameters
    
    use cparams, only: mx_dumps 
    use namelist_data, only: input_file_line, input_file_line_number
    use setup_data, only: validation_output, iofilo, iofill, iofilstat, smv_out_interval, iofilsmv, iofilsmvplt, iofilsmvzone, &
        ss_out_interval, iofilssc, iofilssd, iofilssm, iofilssv, iofilssdiag, iofilcalc, stopfile, program_name, &
        errormessage, stime, project, extension
    use option_data, only: total_steps
    
    implicit none

    contains

    ! --------------------------- cfastexit -------------------------------------------

!> \brief   called when CFAST exits, printing an error code if necessary
!> \param   name        routine name calling for exit
!> \param   errorcode   numeric code indicating which call to cfastexit in routine

    subroutine cfastexit (name, errorcode)
    
    character(len=*), intent(in) :: name
    integer, intent(in) :: errorcode
    integer exitcode

    exitcode = errorcode
    if (errorcode/=0) then
        if (trim(name)=='solve_simulation' .and. errorcode==5) then
            ! validation flag test for the maximum iteration exit is because of CFASTBot's testing to make
            !   sure that CFAST can initialize and run a few steps of all the cases in debug mode but doesn't run
            !   to completion. DO NOT CHANGE WITHOUT CHANGING CFASTBOT.
            if (.not.validation_output) write (*, '(''Maximum iteration exit from '',a)') program_name
            if (iofill/=0) write (iofill, '(''Maximum iteration exit from CFAST'',a)') program_name
            exitcode = 0
        else
            if (errormessage/='') write (*,'(a)') errormessage
            if (input_file_line/='') write (*,'(a,i0,a,a)') 'Error on line ',input_file_line_number, &
                ' of the input file: ', trim(input_file_line)
            write (*,'(''***Error exit from '',a,'', error '',i0,'' from routine '',a)') program_name, exitcode, trim(name)
            if (iofill/=0) then
                if (errormessage/='') write (*,'(a)') errormessage
                if (input_file_line/='') write (iofill,'(a,i0,a,a)') 'Error on line ',input_file_line_number, &
                    ' of the input file: ', trim(input_file_line)
                write (iofill,'(''***Error exit from '',a,'', error '',i0,'' from routine '',a)') program_name, &
                exitcode, trim(name)
            end if
        end if
    else
        if (.not.validation_output) write (*, '(''Normal exit from '',a)') program_name
        if (iofill/=0) write (iofill, '(''Normal exit from '',a)') program_name
    end if
    
    call closeoutputfiles
    call delete_output_files (stopfile)
    
    if (exitcode==0) then
        stop
    else
        error stop 1
    end if
    stop
    
    contains 
    
    subroutine writecsvformat (iunit, x, c, nr, nc, nstart, mxr, mxc)

    !     routine: writecsvformat
    !     purpose:writess a comma-delimited file as generated by Micorsoft Excel, assuming that all
    !              the data is in the form of real numbers
    !     arguments: iunit  = logical unit, already open to .csv file
    !                x      = array of dimension (numr,numc) for values in spreadsheet
    !                c      = character array of same dimenaion as x for character values in spreadsheet
    !                nr     = # of rows of arrays x and c
    !                nc     = # of columns of arrays x and c
    !                nstart = starting row of spreadsheet to read
    !                mxr    = actual number of rows read
    !                mxc    = actual number of columns read
    
    integer, intent(in) :: iunit, nr, nc, nstart, mxr, mxc

    real(eb), intent(in) :: x(nr,nc)
    character(len=*), intent(inout) :: c(nr,nc)

    character(len=204800) :: buf
    integer :: i, j, ic, ie
    
    do i = nstart, mxr
        buf = '                    '
        ic = 1
        do j = 1, mxc
            if (x(i,j) /= 0.0) then
                write(c(i,j),'(e16.9)') x(i,j)
            end if
            ie = ic + len_trim(c(i,j))
            buf(ic:ie) = trim(c(i,j))
            ic = ie+1
            buf(ic:ic) = ','
            ic = ic+1
        end do
        write(iunit,'(A)') buf(1:ic)
    end do
    
    end subroutine writecsvformat
    
    end subroutine cfastexit

! --------------------------- delete_output_files -------------------------------------------

    subroutine delete_output_files(outputfile)

    character(len=*), intent(in) :: outputfile
    integer :: fileunit, ios
    logical :: doesthefileexist

    inquire(file=outputfile, exist=doesthefileexist)
    
    if (doesthefileexist) then  ! attempt to open the existing file
        open(newunit=fileunit, file=outputfile, status='old', iostat=ios)
        if (ios /= 0) then  ! if we can't open it, it's likely locked by another app
            write(errormessage,'(a,i0)') 'Error: Could not open file for deletion. Status = ', ios
            call cfastexit('delete_output_files', 1)
        end if
        close(fileunit, status='delete', iostat=ios)  ! close the file and delete it
        if (ios /= 0) then
            write(errormessage,'(a,i0)') 'Error: Could not delete file. Status = ', ios
            call cfastexit('delete_output_files', 1)
        end if
    end if

    end subroutine delete_output_files


    !---------------------closeoutputfiles------------------------------------------------------
    
    subroutine closeoutputfiles

    ! closeoutputfile closes units from open_output_files
    ! Unit numbers defined here and read_input_file

    ! Unit numbers defined for various I/O purposes
    !
    !     iofili        solver.ini and data files (data file, tpp and objects)
    !     iofill        log file
    !     iofilo        output 
    !     iofilstat     write the status file
    !     iofilsmv      smokeview output (header) - note this is rewound each time the plot data is written)
    !     iofilsmvplt   smokeview output (plot data)
    !     iofilsmvzone  smokeview spreadsheet output 
    !     iofilssc      spreadsheet output (compartment and layer related data)
    !     iofilsswd     spreadsheet output (measurement and trigger devices)
    !     iofilssm      spreadsheet output (layer masses)
    !     iofilssv      spreadsheet output (vent flows)
    !     iofilssdiag   spreadsheet output (various diagnostics for verification)
    !     ioresid       diagnostic file of solution vector
    !     ioslab        diagnostic file of flow slabs
    !     iofilcalc     spredsheet output (for monte carlo analysis)
    
    ! other units may be opened with newunit keyword in open statement
    
    logical :: openunit

    ! first the file for "printed" output
    call close_if_open(iofilo)

    ! the status files
    call close_if_open(iofilstat)

    ! the smokeview files
    if (smv_out_interval>0) then
        call close_if_open(iofilsmv)
        call close_if_open(iofilsmvplt)
        call close_if_open(iofilsmvzone)
    end if

    ! the spread sheet files
    if (ss_out_interval>0) then
        ! compartments spreadsheet
        call close_if_open(iofilssc)
        ! devices spreadsheet
        call close_if_open(iofilssd)
        ! masses spreadsheet
        call close_if_open(iofilssm)
        ! vents spreadsheet
        call close_if_open(iofilssv)
        ! diagnostic spreadsheet
        call close_if_open(iofilssdiag)
        ! calculations spreadhseet
        call close_if_open(iofilcalc)
    end if 

    contains

    subroutine close_if_open(unit)

    integer, intent(in) :: unit

    if (unit<=0) return
    inquire(unit, opened=openunit)
    if (openunit) close(unit)

    end subroutine close_if_open
    
    end subroutine closeoutputfiles
    
end module exit_routines
