      subroutine readcsv (iunit,x,c,numr,numc,nstart,maxr,maxc)
c
c   reads a comma-delimited file as generated by Micorsoft Excel
c   program assumes that all the data is in the form of real numbers
c
c   Variables:
c     iunit  = logical unit, already open to .csv file
c     x      = array of dimension (numr,numc) for values in spreadsheet
c     c      = character array of same dimension as x for character values in spreadsheet
c     numr   = # of rows of array x
c     numc   = # of columns of array x
c     nstart = starting row of spreadsheet to read
c     nr     = actual number of rows read
c     nc     = actual number of columns read
c
	dimension x(numr,numc)
	character in*20000,token*100, c(numr,numc)*(*)
	maxr = 0
	maxc = 0
	do i=1,numr
	  do j=1,numc
	    x(i,j) = 0.
		  c(i,j) = ' '
	  end do
	end do
	if (nstart.gt.1) then
	  do  i=1,nstart-1
	    read (iunit,'(A)') in
        end do 
      end if
	nr=0
20    read (iunit,'(A)',end=100) in
      nr=nr+1
	maxr=max(maxr,nr)
      nc=0
      ic=1
30	icomma=index(in,',')
	if (icomma.ne.0) then
	  if (icomma.eq.ic) then
	    token=' '
	  else
	    token=in(ic:icomma-1)
	  end if
	  ic = icomma+1
	  nc = nc + 1
	  in(1:ic-1)=' '
	  if (nr.le.numr.and.nc.le.numc) then
		c(nr,nc) = token
		if (token(1:1).eq.'''') then
		  c(nr,nc)=token(2:len_trim(token)-1)
		  token=c(nr,nc)
		end if
		if (len_trim(token).ne.0) then
			if (token(len_trim(token):len_trim(token)).eq.'''') 
     '			c(nr,nc)=token(1:len_trim(token)-1)
		end if
	    read (token,'(f100.0)',iostat=ios) x(nr,nc)
		if (ios.ne.0) x(nr,nc) = 0
	  else
		write (*,*) 'Array exceeded, r,c=',nr,nc
	    stop
	  end if
	  go to 30
	end if
	nc = nc + 1
	maxc=max(maxc,nc)
	token = in(ic:ic+100)
	c(nr,nc) = token
	read (token,'(f100.0)',iostat=ios) x(nr,nc)
	if (ios.ne.0) x(nr,nc) = 0
	go to 20
100   continue
      return
      end