#!/bin/bash

$RUNCFAST -d SP_AST SP_AST_Test_1.in
$RUNCFAST -d SP_AST SP_AST_Test_2.in
$RUNCFAST -d SP_AST SP_AST_Test_3.in
$RUNCFAST -d SP_AST SP_AST_Diesel_1p1.in
$RUNCFAST -d SP_AST SP_AST_Diesel_1p9.in
$RUNCFAST -d SP_AST SP_AST_Heptane_1p1.in

$RUNCFAST -d UL_NIST_Vents UL_NIST_Vents_Test_1.in
$RUNCFAST -d UL_NIST_Vents UL_NIST_Vents_Test_2.in
$RUNCFAST -d UL_NIST_Vents UL_NIST_Vents_Test_3.in
$RUNCFAST -d UL_NIST_Vents UL_NIST_Vents_Test_4.in

$RUNCFAST -d UL_NFPRF UL_NFPRF_1_01.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_02.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_03.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_04.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_05.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_06.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_07.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_08.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_09.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_10.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_11.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_12.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_13.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_14.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_15.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_16.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_17.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_18.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_19.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_20.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_21.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_1_22.in

$RUNCFAST -d UL_NFPRF UL_NFPRF_2_01.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_2_02.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_2_03.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_2_04.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_2_05.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_2_06.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_2_07.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_2_08.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_2_09.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_2_10.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_2_11.in
$RUNCFAST -d UL_NFPRF UL_NFPRF_2_12.in

$RUNCFAST -d ATF_Corridors ATF_Corridors_050_kW.in
$RUNCFAST -d ATF_Corridors ATF_Corridors_100_kW.in
$RUNCFAST -d ATF_Corridors ATF_Corridors_240_kW.in
$RUNCFAST -d ATF_Corridors ATF_Corridors_250_kW.in
$RUNCFAST -d ATF_Corridors ATF_Corridors_500_kW.in
$RUNCFAST -d ATF_Corridors ATF_Corridors_Mix_kW.in

$RUNCFAST -d NIST_Dunes_2000 NIST_Dunes_2000_SDC02.in
$RUNCFAST -d NIST_Dunes_2000 NIST_Dunes_2000_SDC05.in
$RUNCFAST -d NIST_Dunes_2000 NIST_Dunes_2000_SDC07.in
$RUNCFAST -d NIST_Dunes_2000 NIST_Dunes_2000_SDC10.in
$RUNCFAST -d NIST_Dunes_2000 NIST_Dunes_2000_SDC33.in
$RUNCFAST -d NIST_Dunes_2000 NIST_Dunes_2000_SDC35.in
$RUNCFAST -d NIST_Dunes_2000 NIST_Dunes_2000_SDC38.in
$RUNCFAST -d NIST_Dunes_2000 NIST_Dunes_2000_SDC39.in

$RUNCFAST -d WTC WTC_01.in
$RUNCFAST -d WTC WTC_02.in
$RUNCFAST -d WTC WTC_03.in
$RUNCFAST -d WTC WTC_04.in
$RUNCFAST -d WTC WTC_05.in
$RUNCFAST -d WTC WTC_06.in

$RUNCFAST -d Vettori_Flat Test_1.in
$RUNCFAST -d Vettori_Flat Test_2.in
$RUNCFAST -d Vettori_Flat Test_3.in
$RUNCFAST -d Vettori_Flat Test_4.in
$RUNCFAST -d Vettori_Flat Test_5.in
$RUNCFAST -d Vettori_Flat Test_6.in
$RUNCFAST -d Vettori_Flat Test_7.in
$RUNCFAST -d Vettori_Flat Test_8.in
$RUNCFAST -d Vettori_Flat Test_9.in
$RUNCFAST -d Vettori_Flat Test_10.in
$RUNCFAST -d Vettori_Flat Test_11.in
$RUNCFAST -d Vettori_Flat Test_12.in
$RUNCFAST -d Vettori_Flat Test_13.in
$RUNCFAST -d Vettori_Flat Test_14.in
$RUNCFAST -d Vettori_Flat Test_15.in
$RUNCFAST -d Vettori_Flat Test_16.in
$RUNCFAST -d Vettori_Flat Test_17.in
$RUNCFAST -d Vettori_Flat Test_18.in
$RUNCFAST -d Vettori_Flat Test_19.in
$RUNCFAST -d Vettori_Flat Test_20.in
$RUNCFAST -d Vettori_Flat Test_21.in
$RUNCFAST -d Vettori_Flat Test_22.in
$RUNCFAST -d Vettori_Flat Test_23.in
$RUNCFAST -d Vettori_Flat Test_24.in
$RUNCFAST -d Vettori_Flat Test_25.in
$RUNCFAST -d Vettori_Flat Test_26.in
$RUNCFAST -d Vettori_Flat Test_27.in
$RUNCFAST -d Vettori_Flat Test_28.in
$RUNCFAST -d Vettori_Flat Test_29.in
$RUNCFAST -d Vettori_Flat Test_30.in
$RUNCFAST -d Vettori_Flat Test_31.in
$RUNCFAST -d Vettori_Flat Test_32.in
$RUNCFAST -d Vettori_Flat Test_33.in
$RUNCFAST -d Vettori_Flat Test_34.in
$RUNCFAST -d Vettori_Flat Test_35.in
$RUNCFAST -d Vettori_Flat Test_36.in
$RUNCFAST -d Vettori_Flat Test_37.in
$RUNCFAST -d Vettori_Flat Test_38.in
$RUNCFAST -d Vettori_Flat Test_39.in
$RUNCFAST -d Vettori_Flat Test_40.in
$RUNCFAST -d Vettori_Flat Test_41.in
$RUNCFAST -d Vettori_Flat Test_42.in
$RUNCFAST -d Vettori_Flat Test_43.in
$RUNCFAST -d Vettori_Flat Test_44.in
$RUNCFAST -d Vettori_Flat Test_45.in

$RUNCFAST -d LLNL_Enclosure LLNL_01.in
$RUNCFAST -d LLNL_Enclosure LLNL_02.in
$RUNCFAST -d LLNL_Enclosure LLNL_03.in
$RUNCFAST -d LLNL_Enclosure LLNL_04.in
$RUNCFAST -d LLNL_Enclosure LLNL_05.in
$RUNCFAST -d LLNL_Enclosure LLNL_06.in
$RUNCFAST -d LLNL_Enclosure LLNL_07.in
$RUNCFAST -d LLNL_Enclosure LLNL_08.in
$RUNCFAST -d LLNL_Enclosure LLNL_09.in
$RUNCFAST -d LLNL_Enclosure LLNL_10.in
$RUNCFAST -d LLNL_Enclosure LLNL_11.in
$RUNCFAST -d LLNL_Enclosure LLNL_12.in
$RUNCFAST -d LLNL_Enclosure LLNL_13.in
$RUNCFAST -d LLNL_Enclosure LLNL_14.in
$RUNCFAST -d LLNL_Enclosure LLNL_15.in
$RUNCFAST -d LLNL_Enclosure LLNL_16.in
$RUNCFAST -d LLNL_Enclosure LLNL_17.in
$RUNCFAST -d LLNL_Enclosure LLNL_18.in
$RUNCFAST -d LLNL_Enclosure LLNL_19.in
$RUNCFAST -d LLNL_Enclosure LLNL_20.in
$RUNCFAST -d LLNL_Enclosure LLNL_21.in
$RUNCFAST -d LLNL_Enclosure LLNL_22.in
$RUNCFAST -d LLNL_Enclosure LLNL_23.in
$RUNCFAST -d LLNL_Enclosure LLNL_24.in
$RUNCFAST -d LLNL_Enclosure LLNL_25.in
$RUNCFAST -d LLNL_Enclosure LLNL_26.in
$RUNCFAST -d LLNL_Enclosure LLNL_27.in
$RUNCFAST -d LLNL_Enclosure LLNL_28.in
$RUNCFAST -d LLNL_Enclosure LLNL_29.in
$RUNCFAST -d LLNL_Enclosure LLNL_30.in
$RUNCFAST -d LLNL_Enclosure LLNL_31.in
$RUNCFAST -d LLNL_Enclosure LLNL_32.in
$RUNCFAST -d LLNL_Enclosure LLNL_33.in
$RUNCFAST -d LLNL_Enclosure LLNL_34.in
$RUNCFAST -d LLNL_Enclosure LLNL_35.in
$RUNCFAST -d LLNL_Enclosure LLNL_36.in
$RUNCFAST -d LLNL_Enclosure LLNL_37.in
$RUNCFAST -d LLNL_Enclosure LLNL_38.in
$RUNCFAST -d LLNL_Enclosure LLNL_39.in
$RUNCFAST -d LLNL_Enclosure LLNL_40.in
$RUNCFAST -d LLNL_Enclosure LLNL_41.in
$RUNCFAST -d LLNL_Enclosure LLNL_42.in
$RUNCFAST -d LLNL_Enclosure LLNL_43.in
$RUNCFAST -d LLNL_Enclosure LLNL_44.in
$RUNCFAST -d LLNL_Enclosure LLNL_45.in
$RUNCFAST -d LLNL_Enclosure LLNL_46.in
$RUNCFAST -d LLNL_Enclosure LLNL_47.in
$RUNCFAST -d LLNL_Enclosure LLNL_48.in
$RUNCFAST -d LLNL_Enclosure LLNL_49.in
$RUNCFAST -d LLNL_Enclosure LLNL_50.in
$RUNCFAST -d LLNL_Enclosure LLNL_51.in
$RUNCFAST -d LLNL_Enclosure LLNL_52.in
$RUNCFAST -d LLNL_Enclosure LLNL_53.in
$RUNCFAST -d LLNL_Enclosure LLNL_54.in
$RUNCFAST -d LLNL_Enclosure LLNL_55.in
$RUNCFAST -d LLNL_Enclosure LLNL_56.in
$RUNCFAST -d LLNL_Enclosure LLNL_57.in
$RUNCFAST -d LLNL_Enclosure LLNL_58.in
$RUNCFAST -d LLNL_Enclosure LLNL_59.in
$RUNCFAST -d LLNL_Enclosure LLNL_60.in
$RUNCFAST -d LLNL_Enclosure LLNL_61.in
$RUNCFAST -d LLNL_Enclosure LLNL_62.in
$RUNCFAST -d LLNL_Enclosure LLNL_63.in
$RUNCFAST -d LLNL_Enclosure LLNL_64.in

$RUNCFAST -d 1RFURN 1RFURN1.in
$RUNCFAST -d 1RFURN 1RFURN6.in

$RUNCFAST -d 1RWALL 1RWALL1.in
$RUNCFAST -d 1RWALL 1RWALL2.in

$RUNCFAST -d FM_NBS FM19.in
$RUNCFAST -d FM_NBS FM21.in

# $RUNCFAST -d Multi Multi

$RUNCFAST -d VTT/Case_1 VTT_C1.in
$RUNCFAST -d VTT/Case_2 VTT_C2.in
$RUNCFAST -d VTT/Case_3 VTT_C3.in

$RUNCFAST -d NIST_NRC/Test_1 NIST_NRC_T1.in
$RUNCFAST -d NIST_NRC/Test_2 NIST_NRC_T2.in
$RUNCFAST -d NIST_NRC/Test_3 NIST_NRC_T3.in
$RUNCFAST -d NIST_NRC/Test_4 NIST_NRC_T4.in
$RUNCFAST -d NIST_NRC/Test_5 NIST_NRC_T5.in
$RUNCFAST -d NIST_NRC/Test_7 NIST_NRC_T7.in
$RUNCFAST -d NIST_NRC/Test_8 NIST_NRC_T8.in
$RUNCFAST -d NIST_NRC/Test_9 NIST_NRC_T9.in
$RUNCFAST -d NIST_NRC/Test_10 NIST_NRC_T10.in
$RUNCFAST -d NIST_NRC/Test_13 NIST_NRC_T13.in
$RUNCFAST -d NIST_NRC/Test_14 NIST_NRC_T14.in
$RUNCFAST -d NIST_NRC/Test_15 NIST_NRC_T15.in
$RUNCFAST -d NIST_NRC/Test_16 NIST_NRC_T16.in
$RUNCFAST -d NIST_NRC/Test_17 NIST_NRC_T17.in
$RUNCFAST -d NIST_NRC/Test_18 NIST_NRC_T18.in

$RUNCFAST -d iBMB_4 iBMB_4_T1.in
$RUNCFAST -d iBMB_5 iBMB_5_T4.in

$RUNCFAST -d FM_SNL FMSNL_1.in
$RUNCFAST -d FM_SNL FMSNL_2.in
$RUNCFAST -d FM_SNL FMSNL_3.in
$RUNCFAST -d FM_SNL FMSNL_4.in
$RUNCFAST -d FM_SNL FMSNL_5.in
$RUNCFAST -d FM_SNL FMSNL_6.in
$RUNCFAST -d FM_SNL FMSNL_7.in
$RUNCFAST -d FM_SNL FMSNL_8.in
$RUNCFAST -d FM_SNL FMSNL_9.in
$RUNCFAST -d FM_SNL FMSNL_10.in
$RUNCFAST -d FM_SNL FMSNL_11.in
$RUNCFAST -d FM_SNL FMSNL_12.in
$RUNCFAST -d FM_SNL FMSNL_13.in
$RUNCFAST -d FM_SNL FMSNL_14.in
$RUNCFAST -d FM_SNL FMSNL_15.in
$RUNCFAST -d FM_SNL FMSNL_16.in
$RUNCFAST -d FM_SNL FMSNL_17.in
$RUNCFAST -d FM_SNL FMSNL_21.in
$RUNCFAST -d FM_SNL FMSNL_22.in

$RUNCFAST -d NBS/MV100A MV100A.in
$RUNCFAST -d NBS/MV100O MV100O.in
$RUNCFAST -d NBS/MV100Z MV100Z.in

$RUNCFAST -d High_Bay USN_Hawaii_Test_01.in
$RUNCFAST -d High_Bay USN_Hawaii_Test_02.in
$RUNCFAST -d High_Bay USN_Hawaii_Test_03.in
$RUNCFAST -d High_Bay USN_Hawaii_Test_04.in
$RUNCFAST -d High_Bay USN_Hawaii_Test_05.in
$RUNCFAST -d High_Bay USN_Hawaii_Test_06.in
$RUNCFAST -d High_Bay USN_Hawaii_Test_07.in
$RUNCFAST -d High_Bay USN_Hawaii_Test_11.in
$RUNCFAST -d High_Bay USN_Iceland_Test_01.in
$RUNCFAST -d High_Bay USN_Iceland_Test_02.in
$RUNCFAST -d High_Bay USN_Iceland_Test_03.in
$RUNCFAST -d High_Bay USN_Iceland_Test_04.in
$RUNCFAST -d High_Bay USN_Iceland_Test_05.in
$RUNCFAST -d High_Bay USN_Iceland_Test_06.in
$RUNCFAST -d High_Bay USN_Iceland_Test_07.in
$RUNCFAST -d High_Bay USN_Iceland_Test_09.in
$RUNCFAST -d High_Bay USN_Iceland_Test_10.in
$RUNCFAST -d High_Bay USN_Iceland_Test_11.in
$RUNCFAST -d High_Bay USN_Iceland_Test_12.in
$RUNCFAST -d High_Bay USN_Iceland_Test_13.in
$RUNCFAST -d High_Bay USN_Iceland_Test_14.in
$RUNCFAST -d High_Bay USN_Iceland_Test_15.in
$RUNCFAST -d High_Bay USN_Iceland_Test_17.in
$RUNCFAST -d High_Bay USN_Iceland_Test_18.in
$RUNCFAST -d High_Bay USN_Iceland_Test_19.in
$RUNCFAST -d High_Bay USN_Iceland_Test_20.in

$RUNCFAST -d Steckler_Compartment Steckler_010.in
$RUNCFAST -d Steckler_Compartment Steckler_011.in
$RUNCFAST -d Steckler_Compartment Steckler_012.in
$RUNCFAST -d Steckler_Compartment Steckler_013.in
$RUNCFAST -d Steckler_Compartment Steckler_014.in
$RUNCFAST -d Steckler_Compartment Steckler_016.in
$RUNCFAST -d Steckler_Compartment Steckler_017.in
$RUNCFAST -d Steckler_Compartment Steckler_018.in
$RUNCFAST -d Steckler_Compartment Steckler_019.in
$RUNCFAST -d Steckler_Compartment Steckler_020.in
$RUNCFAST -d Steckler_Compartment Steckler_021.in
$RUNCFAST -d Steckler_Compartment Steckler_022.in
$RUNCFAST -d Steckler_Compartment Steckler_023.in
$RUNCFAST -d Steckler_Compartment Steckler_030.in
$RUNCFAST -d Steckler_Compartment Steckler_041.in
$RUNCFAST -d Steckler_Compartment Steckler_114.in
$RUNCFAST -d Steckler_Compartment Steckler_116.in
$RUNCFAST -d Steckler_Compartment Steckler_122.in
$RUNCFAST -d Steckler_Compartment Steckler_144.in
$RUNCFAST -d Steckler_Compartment Steckler_160.in
$RUNCFAST -d Steckler_Compartment Steckler_161.in
$RUNCFAST -d Steckler_Compartment Steckler_162.in
$RUNCFAST -d Steckler_Compartment Steckler_163.in
$RUNCFAST -d Steckler_Compartment Steckler_164.in
$RUNCFAST -d Steckler_Compartment Steckler_165.in
$RUNCFAST -d Steckler_Compartment Steckler_166.in
$RUNCFAST -d Steckler_Compartment Steckler_167.in
$RUNCFAST -d Steckler_Compartment Steckler_210.in
$RUNCFAST -d Steckler_Compartment Steckler_212.in
$RUNCFAST -d Steckler_Compartment Steckler_220.in
$RUNCFAST -d Steckler_Compartment Steckler_221.in
$RUNCFAST -d Steckler_Compartment Steckler_224.in
$RUNCFAST -d Steckler_Compartment Steckler_240.in
$RUNCFAST -d Steckler_Compartment Steckler_242.in
$RUNCFAST -d Steckler_Compartment Steckler_310.in
$RUNCFAST -d Steckler_Compartment Steckler_324.in
$RUNCFAST -d Steckler_Compartment Steckler_410.in
$RUNCFAST -d Steckler_Compartment Steckler_510.in
$RUNCFAST -d Steckler_Compartment Steckler_512.in
$RUNCFAST -d Steckler_Compartment Steckler_513.in
$RUNCFAST -d Steckler_Compartment Steckler_514.in
$RUNCFAST -d Steckler_Compartment Steckler_517.in
$RUNCFAST -d Steckler_Compartment Steckler_520.in
$RUNCFAST -d Steckler_Compartment Steckler_521.in
$RUNCFAST -d Steckler_Compartment Steckler_522.in
$RUNCFAST -d Steckler_Compartment Steckler_524.in
$RUNCFAST -d Steckler_Compartment Steckler_540.in
$RUNCFAST -d Steckler_Compartment Steckler_541.in
$RUNCFAST -d Steckler_Compartment Steckler_542.in
$RUNCFAST -d Steckler_Compartment Steckler_544.in
$RUNCFAST -d Steckler_Compartment Steckler_610.in
$RUNCFAST -d Steckler_Compartment Steckler_612.in
$RUNCFAST -d Steckler_Compartment Steckler_622.in
$RUNCFAST -d Steckler_Compartment Steckler_710.in
$RUNCFAST -d Steckler_Compartment Steckler_810.in

$RUNCFAST -d ../Verification/Energy_Balance sealed_test.in
$RUNCFAST -d ../Verification/Energy_Balance sealed_test_2_layers.in

$RUNCFAST -d ../Verification/Mass_Balance species_mass_1.in
$RUNCFAST -d ../Verification/Mass_Balance species_mass_2.in
$RUNCFAST -d ../Verification/Mass_Balance species_mass_3.in
$RUNCFAST -d ../Verification/Mass_Balance species_mass_4.in

$RUNCFAST -d ../Verification/Thermal_Equilibrium basic_tempequilib.in
$RUNCFAST -d ../Verification/Thermal_Equilibrium basic_tempequilib_window.in
$RUNCFAST -d ../Verification/Thermal_Equilibrium basic_tempequilib_window_elevation.in

$RUNCFAST -d ../Verification/Ventilation ventilation_1.in
$RUNCFAST -d ../Verification/Ventilation ventilation_2.in
$RUNCFAST -d ../Verification/Ventilation ventilation_3.in
$RUNCFAST -d ../Verification/Ventilation ventilation_4.in

$RUNCFAST -d ../Verification/Sprinkler sprinkler_1.in



