      SUBROUTINE FLOGO1(DIRS12,YSLAB,XMSLAB,NSLAB,YLAY,QSLAB,PSLAB,
     +    MXPRD,NPROD,MXSLAB,UFLW2)
      include "precis.fi"
C*BEG
C***  FLOGO1  GENERIC - DEPOSITION OF MASS, ENTHALPY, OXYGEN, AND OTHER
C             PRODUCT-OF-COMBUSTION FLOWS PASSING BETWEEN TWO ROOMS
C             THROUGH A VERTICAL, CONSTANT-WIDTH VENT.  THIS VERSION
C             IMPLEMENTS THE CFAST RULES FOR FLOW DEPOSTION. (UPPER
C             LAYER TO UPPER LAYER AND LOWER LAYER TO LOWER LAYER)
C
C*** SUBROUTINE ARGUMENTS
C
C    INPUT
C    -----
C   DIRS12 - A MEASURE OF THE DIRECTION OF THE ROOM 1 TO ROOM
C                       2 FLOW IN EACH SLAB
C   YSLAB - SLAB HEIGHTS IN ROOMS 1,2 ABOVE DATUM ELEVATION [M]
C   XMSLAB - MASS FLOW RATE IN SLABS [KG/S]
C   NSLAB  - NUMBER OF SLABS BETWEEN BOTTOM AND TOP OF VENT
C   YLAY   - HEIGHT OF LAYER IN EACH ROOM ABOVE DATUM ELEVATION [M]
C   QSLAB  - ENTHALPY FLOW RATE IN EACH SLAB [W]
C   PSLAB  - FLOW RATE OF PRODUCT IN EACH SLAB [(UNIT OF PRODUCT/S]
C   MXPRD  - MAXIMUM NUMBER OF PRODUCTS CURRENTLY AVAILABLE.
C   NPROD  - NUMBER OF PRODUCTS
C   MXSLAB - MAXIMUM NUMBER OF SLABS CURRENTLY AVAILABLE.
C
C   OUTPUT
C   ------
C   UFLW2(I,1,J), I=1 OR 2, J=1 OR 2 - MASS FLOW RATE TO UPPER
C            (J=2) OR LOWER (J=1) LAYER OF ROOM I DUE TO ALL SLAB
C            FLOWS OF VENT [KG/S]
C   UFLW2(I,2,J), I=1 OR 2, J=1 OR 2 - ENTHALPY FLOW RATE TO UPPER
C            (J=2) OR LOWER (J=1) LAYER OF ROOM I DUE TO ALL SLAB
C            FLOWS OF VENT [W]
C   UFLW2(I,3,J), I=1 OR 2, J=1 OR 2 - OXYGEN FLOW RATE TO UPPER (J=2)
C            OR LOWER (J=1) LAYER OF ROOM I DUE TO ALL SLAB FLOWS OF
C            VENT [(KG OXYGEN)/S]
C   UFLW2(I,3+K,J), I=1 OR 2, K=2 TO NPROD, J=1 OR 2 - PRODUCT K FLOW
C            RATE TO UPPER (J=2) OR LOWER (J=1) LAYER OF ROOM I DUE
C            TO ALL SLAB FLOWS OF VENT [(UNIT PRODUCT K)/S]
C*END
      include "flwptrs.fi"
      INTEGER DIRS12(*)
      DIMENSION YSLAB(*), XMSLAB(*), QSLAB(*), YLAY(*), 
     +    PSLAB(MXSLAB,*)
      DIMENSION UFLW2(2,MXPRD+2,2), FF(2)
C
C*** INITIALIZE OUTPUTS
C
      DO 20 I = 1, 2
        DO 10 IPROD = 1, NPROD + 2
          UFLW2(I,IPROD,L) = 0.0D0
          UFLW2(I,IPROD,U) = 0.0D0
   10   CONTINUE
   20 CONTINUE
C
C*** PUT EACH SLAB FLOW INTO APPROPRIATE LAYER OF ROOM ITO
C    AND TAKE SLAB FLOW OUT OF APPROPRIATE LAYER OF ROOM IFROM
C
      DO 70 N = 1, NSLAB
C
C*** DETERMINE WHERE ROOM FLOW IS COMING FROM
C
        IF (DIRS12(N).EQ.1) THEN
          IFROM = 1
          ITO = 2
        ELSE IF (DIRS12(N).EQ.-1) THEN
          IFROM = 2
          ITO = 1
        ELSE
C
C*** NO FLOW IN THIS SLAB SO WE CAN SKIP IT
C
          GO TO 70
        END IF
C
C*** LOWER TO LOWER OR UPPER TO UPPER
C
        IF (YSLAB(N).GE.YLAY(IFROM)) THEN
          FU = 1.0D0
        ELSE
          FU = 0.0D0
        END IF
        FL = 1.0D0 - FU
        FF(L) = FL
        FF(U) = FU
C
C*** PUT FLOW INTO DESTINATION ROOM
C
        XMTERM = XMSLAB(N)
        QTERM = QSLAB(N)
        DO 40 ILAY = 1, 2
          UFLW2(ITO,M,ILAY) = UFLW2(ITO,M,ILAY) + FF(ILAY) * XMTERM
          UFLW2(ITO,Q,ILAY) = UFLW2(ITO,Q,ILAY) + FF(ILAY) * QTERM
          DO 30 IPROD = 1, NPROD
            UFLW2(ITO,2+IPROD,ILAY) = UFLW2(ITO,2+IPROD,ILAY) + 
     +          FF(ILAY) * PSLAB(N,IPROD)
   30     CONTINUE
   40   CONTINUE
C
C*** TAKE IT OUT OF THE ORIGIN ROOM
C
        IF (YSLAB(N).GE.YLAY(IFROM)) THEN
          UFLW2(IFROM,M,U) = UFLW2(IFROM,M,U) - XMTERM
          UFLW2(IFROM,Q,U) = UFLW2(IFROM,Q,U) - QTERM
          DO 50 IPROD = 1, NPROD
            UFLW2(IFROM,2+IPROD,U) = UFLW2(IFROM,2+IPROD,U) - 
     +          PSLAB(N,IPROD)
   50     CONTINUE
        ELSE
          UFLW2(IFROM,M,L) = UFLW2(IFROM,M,L) - XMTERM
          UFLW2(IFROM,Q,L) = UFLW2(IFROM,Q,L) - QTERM
          DO 60 IPROD = 1, NPROD
            UFLW2(IFROM,2+IPROD,L) = UFLW2(IFROM,2+IPROD,L) - 
     +          PSLAB(N,IPROD)
   60     CONTINUE
        END IF
   70 CONTINUE
      RETURN
      END
