      CHARACTER FUNCTION TOUPPER(CH)
      CHARACTER*1 CH, TOLOWER
C
C     CONVERT TO UPPER CASE
C
      ICH = ICHAR(CH)
      IF (ICH.GT.96.AND.ICH.LT.123) ICH = ICH - 32
      TOUPPER = CHAR(ICH)
      RETURN
C
C     COVERT TO LOWER CASE
C
      ENTRY TOLOWER(CH)
      ICH = ICHAR(CH)
      IF (ICH.GT.64.AND.ICH.LT.91) ICH = ICH + 32
      TOLOWER = CHAR(ICH)
      RETURN
      END
