<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class Fire_Advanced
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(Fire_Advanced))
        Me.FirePlot = New NPlot.Windows.PlotSurface2D()
        Me.FireDataSS = New C1.Win.C1FlexGrid.C1FlexGrid()
        Me.t2Cancel = New System.Windows.Forms.Button()
        Me.t2OK = New System.Windows.Forms.Button()
        Me.GroupBox9 = New System.Windows.Forms.GroupBox()
        Me.Label2 = New System.Windows.Forms.Label()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.FireTSName = New System.Windows.Forms.ComboBox()
        Me.FireSootName = New System.Windows.Forms.ComboBox()
        Me.FireHCNName = New System.Windows.Forms.ComboBox()
        Me.FireHClName = New System.Windows.Forms.ComboBox()
        Me.FireCOName = New System.Windows.Forms.ComboBox()
        Me.FireHeightName = New System.Windows.Forms.ComboBox()
        Me.FireAreaName = New System.Windows.Forms.ComboBox()
        Me.FireHRRName = New System.Windows.Forms.ComboBox()
        Me.FireHRR = New System.Windows.Forms.TextBox()
        Me.Label67 = New System.Windows.Forms.Label()
        Me.FireHCNYield = New System.Windows.Forms.TextBox()
        Me.FireTSYield = New System.Windows.Forms.TextBox()
        Me.Label115 = New System.Windows.Forms.Label()
        Me.Label66 = New System.Windows.Forms.Label()
        Me.FireArea = New System.Windows.Forms.TextBox()
        Me.Label95 = New System.Windows.Forms.Label()
        Me.FireHClYield = New System.Windows.Forms.TextBox()
        Me.FireSootYield = New System.Windows.Forms.TextBox()
        Me.Label36 = New System.Windows.Forms.Label()
        Me.Label105 = New System.Windows.Forms.Label()
        Me.Label108 = New System.Windows.Forms.Label()
        Me.FireHoC = New System.Windows.Forms.TextBox()
        Me.FireRadiativeFraction = New System.Windows.Forms.TextBox()
        Me.Label113 = New System.Windows.Forms.Label()
        Me.FireHeight = New System.Windows.Forms.TextBox()
        Me.FireCOYield = New System.Windows.Forms.TextBox()
        Me.Label60 = New System.Windows.Forms.Label()
        Me.Label71 = New System.Windows.Forms.Label()
        CType(Me.FireDataSS, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.GroupBox9.SuspendLayout()
        Me.SuspendLayout()
        '
        'FirePlot
        '
        Me.FirePlot.AutoScaleAutoGeneratedAxes = True
        Me.FirePlot.AutoScaleTitle = False
        Me.FirePlot.BackColor = System.Drawing.SystemColors.ControlLightLight
        Me.FirePlot.DateTimeToolTip = False
        Me.FirePlot.Legend = Nothing
        Me.FirePlot.LegendZOrder = -1
        Me.FirePlot.Location = New System.Drawing.Point(406, 293)
        Me.FirePlot.Name = "FirePlot"
        Me.FirePlot.RightMenu = Nothing
        Me.FirePlot.ShowCoordinates = True
        Me.FirePlot.Size = New System.Drawing.Size(509, 223)
        Me.FirePlot.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None
        Me.FirePlot.TabIndex = 729
        Me.FirePlot.TabStop = False
        Me.FirePlot.Title = ""
        Me.FirePlot.TitleFont = New System.Drawing.Font("Arial", 14.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel)
        Me.FirePlot.XAxis1 = Nothing
        Me.FirePlot.XAxis2 = Nothing
        Me.FirePlot.YAxis1 = Nothing
        Me.FirePlot.YAxis2 = Nothing
        '
        'FireDataSS
        '
        Me.FireDataSS.AllowDelete = True
        Me.FireDataSS.AllowDragging = C1.Win.C1FlexGrid.AllowDraggingEnum.None
        Me.FireDataSS.AllowResizing = C1.Win.C1FlexGrid.AllowResizingEnum.None
        Me.FireDataSS.AllowSorting = C1.Win.C1FlexGrid.AllowSortingEnum.None
        Me.FireDataSS.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Bottom), System.Windows.Forms.AnchorStyles)
        Me.FireDataSS.AutoClipboard = True
        Me.FireDataSS.ColumnInfo = resources.GetString("FireDataSS.ColumnInfo")
        Me.FireDataSS.ExtendLastCol = True
        Me.FireDataSS.Location = New System.Drawing.Point(325, 47)
        Me.FireDataSS.Name = "FireDataSS"
        Me.FireDataSS.Rows.Count = 101
        Me.FireDataSS.Rows.DefaultSize = 17
        Me.FireDataSS.ScrollBars = System.Windows.Forms.ScrollBars.Vertical
        Me.FireDataSS.Size = New System.Drawing.Size(671, 223)
        Me.FireDataSS.TabIndex = 730
        '
        't2Cancel
        '
        Me.t2Cancel.DialogResult = System.Windows.Forms.DialogResult.Cancel
        Me.t2Cancel.Location = New System.Drawing.Point(176, 447)
        Me.t2Cancel.Name = "t2Cancel"
        Me.t2Cancel.Size = New System.Drawing.Size(75, 23)
        Me.t2Cancel.TabIndex = 732
        Me.t2Cancel.Text = "Cancel"
        Me.t2Cancel.UseVisualStyleBackColor = True
        '
        't2OK
        '
        Me.t2OK.DialogResult = System.Windows.Forms.DialogResult.OK
        Me.t2OK.Location = New System.Drawing.Point(73, 447)
        Me.t2OK.Name = "t2OK"
        Me.t2OK.Size = New System.Drawing.Size(75, 23)
        Me.t2OK.TabIndex = 731
        Me.t2OK.Text = "OK"
        Me.t2OK.UseVisualStyleBackColor = True
        '
        'GroupBox9
        '
        Me.GroupBox9.Controls.Add(Me.Label2)
        Me.GroupBox9.Controls.Add(Me.Label1)
        Me.GroupBox9.Controls.Add(Me.FireTSName)
        Me.GroupBox9.Controls.Add(Me.FireSootName)
        Me.GroupBox9.Controls.Add(Me.FireHCNName)
        Me.GroupBox9.Controls.Add(Me.FireHClName)
        Me.GroupBox9.Controls.Add(Me.FireCOName)
        Me.GroupBox9.Controls.Add(Me.FireHeightName)
        Me.GroupBox9.Controls.Add(Me.FireAreaName)
        Me.GroupBox9.Controls.Add(Me.FireHRRName)
        Me.GroupBox9.Controls.Add(Me.FireHRR)
        Me.GroupBox9.Controls.Add(Me.Label67)
        Me.GroupBox9.Controls.Add(Me.FireHCNYield)
        Me.GroupBox9.Controls.Add(Me.FireTSYield)
        Me.GroupBox9.Controls.Add(Me.Label115)
        Me.GroupBox9.Controls.Add(Me.Label66)
        Me.GroupBox9.Controls.Add(Me.FireArea)
        Me.GroupBox9.Controls.Add(Me.Label95)
        Me.GroupBox9.Controls.Add(Me.FireHClYield)
        Me.GroupBox9.Controls.Add(Me.FireSootYield)
        Me.GroupBox9.Controls.Add(Me.Label36)
        Me.GroupBox9.Controls.Add(Me.Label105)
        Me.GroupBox9.Controls.Add(Me.Label108)
        Me.GroupBox9.Controls.Add(Me.FireHoC)
        Me.GroupBox9.Controls.Add(Me.FireRadiativeFraction)
        Me.GroupBox9.Controls.Add(Me.Label113)
        Me.GroupBox9.Controls.Add(Me.FireHeight)
        Me.GroupBox9.Controls.Add(Me.FireCOYield)
        Me.GroupBox9.Controls.Add(Me.Label60)
        Me.GroupBox9.Controls.Add(Me.Label71)
        Me.GroupBox9.Location = New System.Drawing.Point(15, 47)
        Me.GroupBox9.Name = "GroupBox9"
        Me.GroupBox9.Size = New System.Drawing.Size(304, 361)
        Me.GroupBox9.TabIndex = 740
        Me.GroupBox9.TabStop = False
        Me.GroupBox9.Text = "Fire Properties"
        '
        'Label2
        '
        Me.Label2.AutoSize = True
        Me.Label2.Location = New System.Drawing.Point(245, 38)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(18, 13)
        Me.Label2.TabIndex = 750
        Me.Label2.Text = "ID"
        '
        'Label1
        '
        Me.Label1.Location = New System.Drawing.Point(117, 25)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(80, 26)
        Me.Label1.TabIndex = 749
        Me.Label1.Text = "Reset to Constant Value"
        Me.Label1.TextAlign = System.Drawing.ContentAlignment.TopCenter
        '
        'FireTSName
        '
        Me.FireTSName.ItemHeight = 13
        Me.FireTSName.Items.AddRange(New Object() {"Time", "Temperature", "Heat Flux"})
        Me.FireTSName.Location = New System.Drawing.Point(214, 314)
        Me.FireTSName.Name = "FireTSName"
        Me.FireTSName.Size = New System.Drawing.Size(80, 21)
        Me.FireTSName.TabIndex = 748
        Me.FireTSName.Text = "Time"
        '
        'FireSootName
        '
        Me.FireSootName.ItemHeight = 13
        Me.FireSootName.Items.AddRange(New Object() {"Time", "Temperature", "Heat Flux"})
        Me.FireSootName.Location = New System.Drawing.Point(214, 286)
        Me.FireSootName.Name = "FireSootName"
        Me.FireSootName.Size = New System.Drawing.Size(80, 21)
        Me.FireSootName.TabIndex = 747
        Me.FireSootName.Text = "Time"
        '
        'FireHCNName
        '
        Me.FireHCNName.ItemHeight = 13
        Me.FireHCNName.Items.AddRange(New Object() {"Time", "Temperature", "Heat Flux"})
        Me.FireHCNName.Location = New System.Drawing.Point(214, 258)
        Me.FireHCNName.Name = "FireHCNName"
        Me.FireHCNName.Size = New System.Drawing.Size(80, 21)
        Me.FireHCNName.TabIndex = 746
        Me.FireHCNName.Text = "Time"
        '
        'FireHClName
        '
        Me.FireHClName.ItemHeight = 13
        Me.FireHClName.Items.AddRange(New Object() {"Time", "Temperature", "Heat Flux"})
        Me.FireHClName.Location = New System.Drawing.Point(214, 230)
        Me.FireHClName.Name = "FireHClName"
        Me.FireHClName.Size = New System.Drawing.Size(80, 21)
        Me.FireHClName.TabIndex = 745
        Me.FireHClName.Text = "Time"
        '
        'FireCOName
        '
        Me.FireCOName.ItemHeight = 13
        Me.FireCOName.Items.AddRange(New Object() {"Time", "Temperature", "Heat Flux"})
        Me.FireCOName.Location = New System.Drawing.Point(214, 202)
        Me.FireCOName.Name = "FireCOName"
        Me.FireCOName.Size = New System.Drawing.Size(80, 21)
        Me.FireCOName.TabIndex = 744
        Me.FireCOName.Text = "Time"
        '
        'FireHeightName
        '
        Me.FireHeightName.ItemHeight = 13
        Me.FireHeightName.Items.AddRange(New Object() {"Time", "Temperature", "Heat Flux"})
        Me.FireHeightName.Location = New System.Drawing.Point(214, 174)
        Me.FireHeightName.Name = "FireHeightName"
        Me.FireHeightName.Size = New System.Drawing.Size(80, 21)
        Me.FireHeightName.TabIndex = 743
        Me.FireHeightName.Text = "Time"
        '
        'FireAreaName
        '
        Me.FireAreaName.ItemHeight = 13
        Me.FireAreaName.Items.AddRange(New Object() {"Time", "Temperature", "Heat Flux"})
        Me.FireAreaName.Location = New System.Drawing.Point(214, 146)
        Me.FireAreaName.Name = "FireAreaName"
        Me.FireAreaName.Size = New System.Drawing.Size(80, 21)
        Me.FireAreaName.TabIndex = 742
        Me.FireAreaName.Text = "Time"
        '
        'FireHRRName
        '
        Me.FireHRRName.ItemHeight = 13
        Me.FireHRRName.Items.AddRange(New Object() {"Time", "Temperature", "Heat Flux"})
        Me.FireHRRName.Location = New System.Drawing.Point(214, 62)
        Me.FireHRRName.Name = "FireHRRName"
        Me.FireHRRName.Size = New System.Drawing.Size(80, 21)
        Me.FireHRRName.TabIndex = 739
        Me.FireHRRName.Text = "Time"
        '
        'FireHRR
        '
        Me.FireHRR.Location = New System.Drawing.Point(117, 62)
        Me.FireHRR.Name = "FireHRR"
        Me.FireHRR.Size = New System.Drawing.Size(80, 20)
        Me.FireHRR.TabIndex = 735
        '
        'Label67
        '
        Me.Label67.AutoSize = True
        Me.Label67.Location = New System.Drawing.Point(83, 66)
        Me.Label67.Name = "Label67"
        Me.Label67.Size = New System.Drawing.Size(34, 13)
        Me.Label67.TabIndex = 734
        Me.Label67.Text = "HRR:"
        Me.Label67.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'FireHCNYield
        '
        Me.FireHCNYield.Location = New System.Drawing.Point(117, 258)
        Me.FireHCNYield.Name = "FireHCNYield"
        Me.FireHCNYield.Size = New System.Drawing.Size(80, 20)
        Me.FireHCNYield.TabIndex = 733
        '
        'FireTSYield
        '
        Me.FireTSYield.Location = New System.Drawing.Point(117, 314)
        Me.FireTSYield.Name = "FireTSYield"
        Me.FireTSYield.Size = New System.Drawing.Size(80, 20)
        Me.FireTSYield.TabIndex = 717
        '
        'Label115
        '
        Me.Label115.AutoSize = True
        Me.Label115.Location = New System.Drawing.Point(67, 318)
        Me.Label115.Name = "Label115"
        Me.Label115.Size = New System.Drawing.Size(50, 13)
        Me.Label115.TabIndex = 159
        Me.Label115.Text = "TS Yield:"
        Me.Label115.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'Label66
        '
        Me.Label66.AutoSize = True
        Me.Label66.Location = New System.Drawing.Point(58, 262)
        Me.Label66.Name = "Label66"
        Me.Label66.Size = New System.Drawing.Size(59, 13)
        Me.Label66.TabIndex = 732
        Me.Label66.Text = "HCN Yield:"
        Me.Label66.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'FireArea
        '
        Me.FireArea.Location = New System.Drawing.Point(117, 146)
        Me.FireArea.Name = "FireArea"
        Me.FireArea.Size = New System.Drawing.Size(80, 20)
        Me.FireArea.TabIndex = 737
        '
        'Label95
        '
        Me.Label95.AutoSize = True
        Me.Label95.Location = New System.Drawing.Point(65, 150)
        Me.Label95.Name = "Label95"
        Me.Label95.Size = New System.Drawing.Size(52, 13)
        Me.Label95.TabIndex = 736
        Me.Label95.Text = "Fire Area:"
        Me.Label95.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'FireHClYield
        '
        Me.FireHClYield.Location = New System.Drawing.Point(117, 230)
        Me.FireHClYield.Name = "FireHClYield"
        Me.FireHClYield.Size = New System.Drawing.Size(80, 20)
        Me.FireHClYield.TabIndex = 731
        '
        'FireSootYield
        '
        Me.FireSootYield.Location = New System.Drawing.Point(117, 286)
        Me.FireSootYield.Name = "FireSootYield"
        Me.FireSootYield.Size = New System.Drawing.Size(80, 20)
        Me.FireSootYield.TabIndex = 715
        '
        'Label36
        '
        Me.Label36.AutoSize = True
        Me.Label36.Location = New System.Drawing.Point(64, 234)
        Me.Label36.Name = "Label36"
        Me.Label36.Size = New System.Drawing.Size(53, 13)
        Me.Label36.TabIndex = 730
        Me.Label36.Text = "HCl Yield:"
        Me.Label36.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'Label105
        '
        Me.Label105.AutoSize = True
        Me.Label105.Location = New System.Drawing.Point(59, 290)
        Me.Label105.Name = "Label105"
        Me.Label105.Size = New System.Drawing.Size(58, 13)
        Me.Label105.TabIndex = 138
        Me.Label105.Text = "Soot Yield:"
        Me.Label105.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'Label108
        '
        Me.Label108.Location = New System.Drawing.Point(10, 86)
        Me.Label108.Name = "Label108"
        Me.Label108.Size = New System.Drawing.Size(107, 28)
        Me.Label108.TabIndex = 116
        Me.Label108.Text = "Heat of Combustion:"
        Me.Label108.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'FireHoC
        '
        Me.FireHoC.Location = New System.Drawing.Point(117, 90)
        Me.FireHoC.Name = "FireHoC"
        Me.FireHoC.Size = New System.Drawing.Size(80, 20)
        Me.FireHoC.TabIndex = 714
        Me.FireHoC.Text = "50000000 J/kg"
        '
        'FireRadiativeFraction
        '
        Me.FireRadiativeFraction.Location = New System.Drawing.Point(117, 118)
        Me.FireRadiativeFraction.Name = "FireRadiativeFraction"
        Me.FireRadiativeFraction.Size = New System.Drawing.Size(80, 20)
        Me.FireRadiativeFraction.TabIndex = 718
        Me.FireRadiativeFraction.Text = "0.3"
        '
        'Label113
        '
        Me.Label113.Location = New System.Drawing.Point(13, 113)
        Me.Label113.Name = "Label113"
        Me.Label113.Size = New System.Drawing.Size(104, 31)
        Me.Label113.TabIndex = 124
        Me.Label113.Text = "Radiative Fraction:"
        Me.Label113.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'FireHeight
        '
        Me.FireHeight.Location = New System.Drawing.Point(117, 174)
        Me.FireHeight.Name = "FireHeight"
        Me.FireHeight.Size = New System.Drawing.Size(80, 20)
        Me.FireHeight.TabIndex = 724
        Me.FireHeight.Text = "0"
        '
        'FireCOYield
        '
        Me.FireCOYield.Location = New System.Drawing.Point(117, 202)
        Me.FireCOYield.Name = "FireCOYield"
        Me.FireCOYield.Size = New System.Drawing.Size(80, 20)
        Me.FireCOYield.TabIndex = 716
        '
        'Label60
        '
        Me.Label60.AutoSize = True
        Me.Label60.Location = New System.Drawing.Point(56, 178)
        Me.Label60.Name = "Label60"
        Me.Label60.Size = New System.Drawing.Size(61, 13)
        Me.Label60.TabIndex = 69
        Me.Label60.Text = "Fire Height:"
        Me.Label60.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'Label71
        '
        Me.Label71.AutoSize = True
        Me.Label71.Location = New System.Drawing.Point(66, 206)
        Me.Label71.Name = "Label71"
        Me.Label71.Size = New System.Drawing.Size(51, 13)
        Me.Label71.TabIndex = 140
        Me.Label71.Text = "CO Yield:"
        Me.Label71.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'Fire_Advanced
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(1008, 562)
        Me.Controls.Add(Me.GroupBox9)
        Me.Controls.Add(Me.t2Cancel)
        Me.Controls.Add(Me.t2OK)
        Me.Controls.Add(Me.FirePlot)
        Me.Controls.Add(Me.FireDataSS)
        Me.MaximumSize = New System.Drawing.Size(1280, 1024)
        Me.MinimumSize = New System.Drawing.Size(1024, 600)
        Me.Name = "Fire_Advanced"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent
        Me.Text = "Advanced Fire Properties"
        CType(Me.FireDataSS, System.ComponentModel.ISupportInitialize).EndInit()
        Me.GroupBox9.ResumeLayout(False)
        Me.GroupBox9.PerformLayout()
        Me.ResumeLayout(False)

    End Sub

    Friend WithEvents FirePlot As NPlot.Windows.PlotSurface2D
    Friend WithEvents FireDataSS As C1.Win.C1FlexGrid.C1FlexGrid
    Friend WithEvents t2Cancel As Button
    Friend WithEvents t2OK As Button
    Friend WithEvents GroupBox9 As GroupBox
    Friend WithEvents FireHRR As TextBox
    Friend WithEvents Label67 As Label
    Friend WithEvents FireHCNYield As TextBox
    Friend WithEvents FireTSYield As TextBox
    Friend WithEvents Label115 As Label
    Friend WithEvents Label66 As Label
    Friend WithEvents FireArea As TextBox
    Friend WithEvents Label95 As Label
    Friend WithEvents FireHClYield As TextBox
    Friend WithEvents FireSootYield As TextBox
    Friend WithEvents Label36 As Label
    Friend WithEvents Label105 As Label
    Friend WithEvents Label108 As Label
    Friend WithEvents FireHoC As TextBox
    Friend WithEvents FireRadiativeFraction As TextBox
    Friend WithEvents Label113 As Label
    Friend WithEvents FireHeight As TextBox
    Friend WithEvents FireCOYield As TextBox
    Friend WithEvents Label60 As Label
    Friend WithEvents Label71 As Label
    Friend WithEvents Label2 As Label
    Friend WithEvents Label1 As Label
    Friend WithEvents FireTSName As ComboBox
    Friend WithEvents FireSootName As ComboBox
    Friend WithEvents FireHCNName As ComboBox
    Friend WithEvents FireHClName As ComboBox
    Friend WithEvents FireCOName As ComboBox
    Friend WithEvents FireHeightName As ComboBox
    Friend WithEvents FireAreaName As ComboBox
    Friend WithEvents FireHRRName As ComboBox
End Class
