      SUBROUTINE BUBBLE (PRSNID,HAZARD,NRET)
C
C   PERFORMS A BUBBLE SORT OF PERSONS INPUT WITH TENAB COMMAND
C
      INTEGER PRSNID(NRET),HAZARD(NRET)
      NRETM1=NRET-1
      DO 20 I=1,NRETM1
      IP1=I+1
      DO 10 J=IP1,NRET
      IF (PRSNID(I)*10+HAZARD(I).GT.PRSNID(J)*10+HAZARD(J)) THEN
        IT=PRSNID(I)
        PRSNID(I)=PRSNID(J)
        PRSNID(J)=IT
        IT=HAZARD(I)
        HAZARD(I)=HAZARD(J)
        HAZARD(J)=IT
      END IF
10    CONTINUE
20    CONTINUE
      RETURN
      END
