      SUBROUTINE CKDUP (PRSNID,HAZARD,NRET)
C
C   CHECK FOR DUPLICATE INPUTS IN PERSON LIST FOR TENAB COMMAND
C
      include "cparams.fi"

      INTEGER PRSNID(NRET),HAZARD(NRET),KEEP(NVM)

      IF (NRET.LE.1) RETURN
      DO 10 I=1,NRET
      IF (HAZARD(I).EQ.8) PRSNID(I)=0
10    CONTINUE
      CALL BUBBLE (PRSNID,HAZARD,NRET)
      KEEP(1)=0
      DO 20 I=2,NRET
      KEEP(I)=0
      IF (PRSNID(I)*10+HAZARD(I).EQ.PRSNID(I-1)*10+HAZARD(I-1)) THEN
        KEEP(I)=1
      END IF
20    CONTINUE
      KOUNT=0
      DO 30 I=1,NRET
      IF (KEEP(I).EQ.0) THEN
        KOUNT=KOUNT+1
        PRSNID(KOUNT)=PRSNID(I)
        HAZARD(KOUNT)=HAZARD(I)
      END IF
30    CONTINUE
      NRET=KOUNT
      RETURN
      END
