      SUBROUTINE DOTENAB (IFILEN,FILE,ERROR,NCSPD,PRSNID,HAZARD,IOU)
C
C   READ IN A LIST OF TENAB VARIABLES
C
      include "cparams.fi"
      include "cplotd.fi"

      INTEGER START,COUNT,FIRST,LAST
      LOGICAL VALID,ERROR
      CHARACTER*128 INBUF
      CHARACTER*63 FILE(MAXFIL)
      INTEGER PRSNID(NVM),HAZARD(NVM)
      DATA IOUNIT/3/
C
      ERROR=.FALSE.
      CALL MESSNRF ('File: ',6)
      CALL READASTU (INBUF,COUNT,START,128,VALID)
      CALL SSTRNGP (INBUF,COUNT,START,FIRST,LAST,VALID)
      IF (.NOT.VALID) RETURN
      NUM=MIN(17,LAST-FIRST+1)
      IFILEN=IFILEN+1
      FILE(IFILEN) = ' '
      FILE(IFILEN)(1:NUM) = INBUF(FIRST:LAST)
      CLOSE(IOUNIT)
      OPEN(UNIT=IOUNIT,FILE=FILE(IFILEN),STATUS='OLD',ERR=1,
     . IOSTAT=IOS,ACCESS='DIRECT',RECL=32,FORM='UNFORMATTED')
      NCSPD=0
      CALL RDPRSN (9,NCSPD,PRSNID,HAZARD)
      IOU=IOUNIT
      RETURN
    1 WRITE(INBUF,2) MOD(IOS,256)
    2 FORMAT(' Error opening TENAB dump file, error = ',I3)
      CALL MESS (INBUF,43)
      ERROR=.TRUE.
      RETURN
      END
