      SUBROUTINE READASTU (IN, COUNT, START, MAX, VALID)

C     READ IN A STRING FROM THE STANDARD INPUT DEVICE

C     THIS VERSION OF READAS(TU) IS SIMILAR TO THE ONE USED BY EVERONE ELSE
C     (READAS) EXCEPT THAT THIS CONTAINS AUTOMATIC CONVERSION TO UPPER CASE.  
C     THIS IS TO FILTER COMMANDS FROM THE CONSOLE SO THAT THEY ARE NOT CASE
C     SENSITIVE.

      include "precis.fi"
      include "cparams.fi"
      include "cshell.fi"

      INTEGER START, COUNT
      LOGICAL VALID
      CHARACTER CH,INN*256,IN(MAX),C

10    INN = ' '
      READ(IOFILI,4,END=5) INN
4     FORMAT(A256)

C     FILTER COMMENTS

      C = INN(1:1)
      IF (C.EQ.'!'.OR.C.EQ.'#') GO TO 10

C     OK

      DO 7 I = 255,1,-1
      COUNT = I
      IF (INN(I:I).NE.' ') GO TO 6
7     CONTINUE
5     COUNT = 0
      VALID = .FALSE.
      RETURN
C
C   CHECK FOR CONTROL CHARACTERS
C
6     NC = 0
      COUNT = MIN(MAX,COUNT)
      DO 1 I = 1,COUNT
      ICH = ICHAR(INN(I:I))
      IF (ICH.LT.32.OR.ICH.GT.125) GO TO 3
      NC = I
1     CONTINUE
3     COUNT = NC
C
C   CONVERT TO UPPER CASE
C
      DO 2 I = 1,COUNT
      CH = INN(I:I)
      ICH = ICHAR(CH)
      IF (ICH.GT.96.AND.ICH.LT.123) ICH = ICH - 32
      IN(I) = CHAR(ICH)
2     CONTINUE
      START=1
      IF (COUNT.GT.0) THEN
        VALID = .TRUE.
      ELSE
        VALID = .FALSE.
      END IF
      RETURN
      END
