      SUBROUTINE SSTRNGP (STRING,WCOUNT,SSTART,SFIRST,SLAST,SVALID)
C
C   THIS ROUTINE FINDS POSITIONS OF SUBSTRINGS WITHIN A CHARACTER
C   STRING.  A SPACE, COMMA, - , (, OR ) INDICATES THE BEGINNING OR
C   END OF A SUBSTRING.  WHEN CALLED, THE STRING IS PASSED
C   AS AN INTEGER(CHOOSE) ALONG WITH THE NUMBER OF CHARACTERS IN THE
C   STRING(WCOUNT) AND A STARTING POSITION(SSTART).  BEGINNING AT
C   "SSTART", THE ROUTINE SEARCHES FOR A SUBSTRING. IF A SUBSTRING IS
C   FOUND, ITS FIRST AND LAST CHARACTER POSITIONS ARE RETURNED ALONG
C   WITH A TRUE VALUE IN "SVALID"; OTHERWISE "SVALID" IS SET FALSE.
C   SIMILAR TO SSTRNG, EXCEPT ENTRIES CAN BE GROUPED WITH PARENTHESIS
C
      LOGICAL SVALID
      INTEGER SFIRST,SLAST,SSTART,WCOUNT,ENDSTR
      CHARACTER*1 STRING(128),SPACE,COMMA,RPAREN,LPAREN
      DATA SPACE /' '/, COMMA /','/,RPAREN /')'/, LPAREN /'('/
c
      SVALID = .TRUE.
      ENDSTR = SSTART + WCOUNT - 1
C
C  FIND POSITION OF FIRST ELEMENT OF SUBSTRING
C
      DO 20 I = SSTART, ENDSTR
C
C   MOVE TO THE BEGINNING OF THE SUBSTRING
C
      SFIRST = I
      IF ((STRING(I).NE.SPACE).AND.(STRING(I).NE.COMMA).AND.
     2 (STRING(I).NE.RPAREN).AND.(STRING(I).NE.LPAREN)) GO TO 60
20    CONTINUE
C
C  NO SUBSTRING FOUND - ONLY DELIMITER
C
      GO TO 40
C
C  FIND POSITION OF LAST CHARACTER OF SUBSTRING
C
60    DO 50 J = SFIRST, ENDSTR
C
C  POSITION OF LAST ELEMENT OF SUBSTRING
C
      SLAST = J-1
      IF ((STRING(J).EQ.SPACE).OR.(STRING(J).EQ.COMMA).OR.
     . (STRING(J).EQ.RPAREN).OR.(STRING(J).EQ.LPAREN)) GO TO 100
50    CONTINUE
C
C  NO SUBSTRING DELIMITER => LAST CHARACTER OF SUBSTRING IS THE
C  LAST CHARACTER OF THE STRING
C
      SLAST = ENDSTR
      RETURN
C
C  NO SUBSTRING FOUND
C
40    SVALID = .FALSE.
      RETURN
100   IF (SLAST.LT.SFIRST) SVALID = .FALSE.
      END
