      SUBROUTINE SSTRNG(STRING,WCOUNT,SSTART,SFIRST,SLAST,SVALID)
C
C  THIS ROUTINE FINDS POSITIONS OF SUBSTRINGS WITHIN A CHARACTER
C  STRING.  A SPACE, COMMA, - , (, OR ) INDICATES THE BEGINNING OR
C  END OF A SUBSTRING.  WHEN CALLED, THE STRING IS PASSED
C  AS AN INTEGER(CHOOSE) ALONG WITH THE NUMBER OF CHARACTERS IN THE
C  STRING(WCOUNT) AND A STARTING POSITION(SSTART).  BEGINNING AT
C  "SSTART", THE ROUTINE SEARCHES FOR A SUBSTRING. IF A SUBSTRING IS
C  FOUND, ITS FIRST AND LAST CHARACTER POSITIONS ARE RETURNED ALONG
C  WITH A TRUE VALUE IN "SVALID"; OTHERWISE "SVALID" IS SET FALSE.
C
      LOGICAL SVALID
      INTEGER SFIRST, SLAST, SSTART, WCOUNT, ENDSTR
      CHARACTER*1 STRING(*), SPACE, COMMA
C
      DATA SPACE/' '/, COMMA/','/
C
      SVALID = .TRUE.
C
C  INVALID STARTING POSITION - PAST END OF STRING
C
      ENDSTR = SSTART + WCOUNT - 1
C
C  FIND POSITION OF FIRST ELEMENT OF SUBSTRING
C
      DO 20 I = SSTART, ENDSTR
C
C     MOVE TO THE BEGINNING OF THE SUBSTRING
C
      SFIRST = I
      IF((STRING(I).NE.SPACE).AND.(STRING(I).NE.COMMA)) GOTO 60
20    CONTINUE
C
C  NO SUBSTRING FOUND - ONLY DELIMITER
C
      GO TO 40
C
C  FIND POSITION OF LAST CHARACTER OF SUBSTRING
C
60    DO 50 J = SFIRST, ENDSTR
C
C  POSITION OF LAST ELEMENT OF SUBSTRING
C
      SLAST = J-1
      IF((STRING(J).EQ.SPACE).OR.(STRING(J).EQ.COMMA)) GO TO 100
50    CONTINUE
C
C  NO SUBSTRING DELIMITER => LAST CHARACTER OF SUBSTRING IS THE
C  LAST CHARACTER OF THE STRING
C
      SLAST = ENDSTR
      RETURN
C
C  NO SUBSTRING FOUND
C
40    SVALID = .FALSE.
100   RETURN
      END
