#!/bin/bash

rm *_compartments.csv /s/q >nul 2>&1
rm *_devices.csv /s/q >nul 2>&1
rm *_masses.csv /s/q >nul 2>&1
rm *_vents.csv /s/q >nul 2>&1
rm *_walls.csv /s/q >nul 2>&1
rm *_calculations.csv /s/q >nul 2>&1
rm *_n.csv /s/q >nul 2>&1
rm *_s.csv /s/q >nul 2>&1
rm *_f.csv /s/q >nul 2>&1
rm *_w.csv /s/q >nul 2>&1
rm *_m.csv /s/q >nul 2>&1
rm *_c.csv /s/q >nul 2>&1
rm *_d.csv /s/q >nul 2>&1
rm *_git.txt /s/q >nul 2>&1
rm *_zone.csv /s/q >nul 2>&1
rm *_resid.csv /s/q >nul 2>&1
rm *_slab.csv /s/q >nul 2>&1
rm *.out /s/q >nul 2>&1
rm *.smv /s/q >nul 2>&1
rm *.plt /s/q >nul 2>&1
rm *.status /s/q >nul 2>&1
rm *.log /s/q >nul 2>&1
rm *.sf /s/q >nul 2>&1
rm *_slice.info /s/q >nul 2>&1
rm *.iso /s/q >nul 2>&1
rm *.sinfo /s/q >nul 2>&1
rm *.err /s/q >nul 2>&1
