<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class EditFireObject
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(EditFireObject))
        Me.FireObjectsCancel = New System.Windows.Forms.Button()
        Me.FireObjectsOK = New System.Windows.Forms.Button()
        Me.FireObjectPlot = New NPlot.Windows.PlotSurface2D()
        Me.FireName = New System.Windows.Forms.TextBox()
        Me.Label9 = New System.Windows.Forms.Label()
        Me.FireDataSS = New C1.Win.C1FlexGrid.C1FlexGrid()
        Me.GroupFireObject = New System.Windows.Forms.GroupBox()
        Me.FireCOYield = New System.Windows.Forms.TextBox()
        Me.Label3 = New System.Windows.Forms.Label()
        Me.FireSootYield = New System.Windows.Forms.TextBox()
        Me.Label2 = New System.Windows.Forms.Label()
        Me.FireCl = New System.Windows.Forms.TextBox()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.FireMaterial = New System.Windows.Forms.ComboBox()
        Me.Label84 = New System.Windows.Forms.Label()
        Me.FireHoC = New System.Windows.Forms.TextBox()
        Me.Label56 = New System.Windows.Forms.Label()
        Me.FireN = New System.Windows.Forms.TextBox()
        Me.FireH = New System.Windows.Forms.TextBox()
        Me.Label64 = New System.Windows.Forms.Label()
        Me.FireC = New System.Windows.Forms.TextBox()
        Me.FireO = New System.Windows.Forms.TextBox()
        Me.Label65 = New System.Windows.Forms.Label()
        Me.Label39 = New System.Windows.Forms.Label()
        Me.Label38 = New System.Windows.Forms.Label()
        Me.Label59 = New System.Windows.Forms.Label()
        Me.FireRadiativeFraction = New System.Windows.Forms.TextBox()
        CType(Me.FireDataSS, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.GroupFireObject.SuspendLayout()
        Me.SuspendLayout()
        '
        'FireObjectsCancel
        '
        Me.FireObjectsCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel
        Me.FireObjectsCancel.Location = New System.Drawing.Point(523, 477)
        Me.FireObjectsCancel.Name = "FireObjectsCancel"
        Me.FireObjectsCancel.Size = New System.Drawing.Size(75, 23)
        Me.FireObjectsCancel.TabIndex = 153
        Me.FireObjectsCancel.Text = "Cancel"
        '
        'FireObjectsOK
        '
        Me.FireObjectsOK.DialogResult = System.Windows.Forms.DialogResult.OK
        Me.FireObjectsOK.Location = New System.Drawing.Point(395, 477)
        Me.FireObjectsOK.Name = "FireObjectsOK"
        Me.FireObjectsOK.Size = New System.Drawing.Size(75, 23)
        Me.FireObjectsOK.TabIndex = 152
        Me.FireObjectsOK.Text = "OK"
        '
        'FireObjectPlot
        '
        Me.FireObjectPlot.AutoScaleAutoGeneratedAxes = True
        Me.FireObjectPlot.AutoScaleTitle = False
        Me.FireObjectPlot.BackColor = System.Drawing.SystemColors.ControlLightLight
        Me.FireObjectPlot.DateTimeToolTip = False
        Me.FireObjectPlot.Legend = Nothing
        Me.FireObjectPlot.LegendZOrder = -1
        Me.FireObjectPlot.Location = New System.Drawing.Point(426, 69)
        Me.FireObjectPlot.Name = "FireObjectPlot"
        Me.FireObjectPlot.RightMenu = Nothing
        Me.FireObjectPlot.ShowCoordinates = True
        Me.FireObjectPlot.Size = New System.Drawing.Size(560, 248)
        Me.FireObjectPlot.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None
        Me.FireObjectPlot.TabIndex = 155
        Me.FireObjectPlot.TabStop = False
        Me.FireObjectPlot.Title = ""
        Me.FireObjectPlot.TitleFont = New System.Drawing.Font("Arial", 14.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel)
        Me.FireObjectPlot.XAxis1 = Nothing
        Me.FireObjectPlot.XAxis2 = Nothing
        Me.FireObjectPlot.YAxis1 = Nothing
        Me.FireObjectPlot.YAxis2 = Nothing
        '
        'FireName
        '
        Me.FireName.Location = New System.Drawing.Point(452, 29)
        Me.FireName.Name = "FireName"
        Me.FireName.Size = New System.Drawing.Size(208, 20)
        Me.FireName.TabIndex = 149
        Me.FireName.Text = "New Fire Object"
        '
        'Label9
        '
        Me.Label9.AutoSize = True
        Me.Label9.Location = New System.Drawing.Point(332, 33)
        Me.Label9.Name = "Label9"
        Me.Label9.Size = New System.Drawing.Size(92, 13)
        Me.Label9.TabIndex = 154
        Me.Label9.Text = "Fire Object Name:"
        Me.Label9.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'FireDataSS
        '
        Me.FireDataSS.AllowDelete = True
        Me.FireDataSS.AllowDragging = C1.Win.C1FlexGrid.AllowDraggingEnum.None
        Me.FireDataSS.AllowResizing = C1.Win.C1FlexGrid.AllowResizingEnum.None
        Me.FireDataSS.AllowSorting = C1.Win.C1FlexGrid.AllowSortingEnum.None
        Me.FireDataSS.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Bottom), System.Windows.Forms.AnchorStyles)
        Me.FireDataSS.AutoClipboard = True
        Me.FireDataSS.ColumnInfo = resources.GetString("FireDataSS.ColumnInfo")
        Me.FireDataSS.ExtendLastCol = True
        Me.FireDataSS.Location = New System.Drawing.Point(189, 341)
        Me.FireDataSS.Name = "FireDataSS"
        Me.FireDataSS.Rows.Count = 101
        Me.FireDataSS.Rows.DefaultSize = 17
        Me.FireDataSS.ScrollBars = System.Windows.Forms.ScrollBars.Vertical
        Me.FireDataSS.Size = New System.Drawing.Size(597, 119)
        Me.FireDataSS.TabIndex = 151
        '
        'GroupFireObject
        '
        Me.GroupFireObject.Controls.Add(Me.FireCOYield)
        Me.GroupFireObject.Controls.Add(Me.Label3)
        Me.GroupFireObject.Controls.Add(Me.FireSootYield)
        Me.GroupFireObject.Controls.Add(Me.Label2)
        Me.GroupFireObject.Controls.Add(Me.FireCl)
        Me.GroupFireObject.Controls.Add(Me.Label1)
        Me.GroupFireObject.Controls.Add(Me.FireMaterial)
        Me.GroupFireObject.Controls.Add(Me.Label84)
        Me.GroupFireObject.Controls.Add(Me.FireHoC)
        Me.GroupFireObject.Controls.Add(Me.Label56)
        Me.GroupFireObject.Controls.Add(Me.FireN)
        Me.GroupFireObject.Controls.Add(Me.FireH)
        Me.GroupFireObject.Controls.Add(Me.Label64)
        Me.GroupFireObject.Controls.Add(Me.FireC)
        Me.GroupFireObject.Controls.Add(Me.FireO)
        Me.GroupFireObject.Controls.Add(Me.Label65)
        Me.GroupFireObject.Controls.Add(Me.Label39)
        Me.GroupFireObject.Controls.Add(Me.Label38)
        Me.GroupFireObject.Controls.Add(Me.Label59)
        Me.GroupFireObject.Controls.Add(Me.FireRadiativeFraction)
        Me.GroupFireObject.Location = New System.Drawing.Point(6, 61)
        Me.GroupFireObject.Name = "GroupFireObject"
        Me.GroupFireObject.Size = New System.Drawing.Size(404, 256)
        Me.GroupFireObject.TabIndex = 150
        Me.GroupFireObject.TabStop = False
        Me.GroupFireObject.Text = "Details"
        '
        'FireCOYield
        '
        Me.FireCOYield.Location = New System.Drawing.Point(297, 118)
        Me.FireCOYield.Name = "FireCOYield"
        Me.FireCOYield.Size = New System.Drawing.Size(80, 20)
        Me.FireCOYield.TabIndex = 139
        '
        'Label3
        '
        Me.Label3.AutoSize = True
        Me.Label3.Location = New System.Drawing.Point(238, 122)
        Me.Label3.Name = "Label3"
        Me.Label3.Size = New System.Drawing.Size(51, 13)
        Me.Label3.TabIndex = 140
        Me.Label3.Text = "CO Yield:"
        Me.Label3.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'FireSootYield
        '
        Me.FireSootYield.Location = New System.Drawing.Point(297, 87)
        Me.FireSootYield.Name = "FireSootYield"
        Me.FireSootYield.Size = New System.Drawing.Size(80, 20)
        Me.FireSootYield.TabIndex = 137
        '
        'Label2
        '
        Me.Label2.AutoSize = True
        Me.Label2.Location = New System.Drawing.Point(231, 91)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(58, 13)
        Me.Label2.TabIndex = 138
        Me.Label2.Text = "Soot Yield:"
        Me.Label2.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'FireCl
        '
        Me.FireCl.Location = New System.Drawing.Point(67, 180)
        Me.FireCl.Name = "FireCl"
        Me.FireCl.Size = New System.Drawing.Size(80, 20)
        Me.FireCl.TabIndex = 135
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Location = New System.Drawing.Point(35, 184)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(19, 13)
        Me.Label1.TabIndex = 136
        Me.Label1.Text = "Cl:"
        Me.Label1.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'FireMaterial
        '
        Me.FireMaterial.ItemHeight = 13
        Me.FireMaterial.Location = New System.Drawing.Point(140, 20)
        Me.FireMaterial.Name = "FireMaterial"
        Me.FireMaterial.Size = New System.Drawing.Size(192, 21)
        Me.FireMaterial.TabIndex = 7
        Me.FireMaterial.Text = "GYPSUM"
        '
        'Label84
        '
        Me.Label84.AutoSize = True
        Me.Label84.Location = New System.Drawing.Point(84, 20)
        Me.Label84.Name = "Label84"
        Me.Label84.Size = New System.Drawing.Size(47, 13)
        Me.Label84.TabIndex = 134
        Me.Label84.Text = "Material:"
        Me.Label84.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'FireHoC
        '
        Me.FireHoC.Location = New System.Drawing.Point(297, 55)
        Me.FireHoC.Name = "FireHoC"
        Me.FireHoC.Size = New System.Drawing.Size(80, 20)
        Me.FireHoC.TabIndex = 13
        Me.FireHoC.Text = "50000000 J/kg"
        '
        'Label56
        '
        Me.Label56.Location = New System.Drawing.Point(217, 53)
        Me.Label56.Name = "Label56"
        Me.Label56.Size = New System.Drawing.Size(72, 24)
        Me.Label56.TabIndex = 116
        Me.Label56.Text = "Heat of Combustion:"
        Me.Label56.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'FireN
        '
        Me.FireN.Location = New System.Drawing.Point(67, 149)
        Me.FireN.Name = "FireN"
        Me.FireN.Size = New System.Drawing.Size(80, 20)
        Me.FireN.TabIndex = 12
        '
        'FireH
        '
        Me.FireH.Location = New System.Drawing.Point(67, 87)
        Me.FireH.Name = "FireH"
        Me.FireH.Size = New System.Drawing.Size(80, 20)
        Me.FireH.TabIndex = 9
        '
        'Label64
        '
        Me.Label64.AutoSize = True
        Me.Label64.Location = New System.Drawing.Point(37, 60)
        Me.Label64.Name = "Label64"
        Me.Label64.Size = New System.Drawing.Size(17, 13)
        Me.Label64.TabIndex = 118
        Me.Label64.Text = "C:"
        Me.Label64.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'FireC
        '
        Me.FireC.Location = New System.Drawing.Point(67, 56)
        Me.FireC.Name = "FireC"
        Me.FireC.Size = New System.Drawing.Size(80, 20)
        Me.FireC.TabIndex = 8
        '
        'FireO
        '
        Me.FireO.Location = New System.Drawing.Point(67, 118)
        Me.FireO.Name = "FireO"
        Me.FireO.Size = New System.Drawing.Size(80, 20)
        Me.FireO.TabIndex = 10
        '
        'Label65
        '
        Me.Label65.AutoSize = True
        Me.Label65.Location = New System.Drawing.Point(36, 122)
        Me.Label65.Name = "Label65"
        Me.Label65.Size = New System.Drawing.Size(18, 13)
        Me.Label65.TabIndex = 122
        Me.Label65.Text = "O:"
        Me.Label65.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'Label39
        '
        Me.Label39.AutoSize = True
        Me.Label39.Location = New System.Drawing.Point(36, 91)
        Me.Label39.Name = "Label39"
        Me.Label39.Size = New System.Drawing.Size(18, 13)
        Me.Label39.TabIndex = 119
        Me.Label39.Text = "H:"
        Me.Label39.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'Label38
        '
        Me.Label38.AutoSize = True
        Me.Label38.Location = New System.Drawing.Point(36, 153)
        Me.Label38.Name = "Label38"
        Me.Label38.Size = New System.Drawing.Size(18, 13)
        Me.Label38.TabIndex = 116
        Me.Label38.Text = "N:"
        Me.Label38.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'Label59
        '
        Me.Label59.Location = New System.Drawing.Point(233, 149)
        Me.Label59.Name = "Label59"
        Me.Label59.Size = New System.Drawing.Size(56, 24)
        Me.Label59.TabIndex = 124
        Me.Label59.Text = "Radiative Fraction:"
        Me.Label59.TextAlign = System.Drawing.ContentAlignment.MiddleRight
        '
        'FireRadiativeFraction
        '
        Me.FireRadiativeFraction.Location = New System.Drawing.Point(297, 151)
        Me.FireRadiativeFraction.Name = "FireRadiativeFraction"
        Me.FireRadiativeFraction.Size = New System.Drawing.Size(80, 20)
        Me.FireRadiativeFraction.TabIndex = 17
        Me.FireRadiativeFraction.Text = "0.3"
        '
        'EditFireObject
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(992, 531)
        Me.Controls.Add(Me.FireObjectsCancel)
        Me.Controls.Add(Me.FireObjectsOK)
        Me.Controls.Add(Me.FireObjectPlot)
        Me.Controls.Add(Me.FireName)
        Me.Controls.Add(Me.Label9)
        Me.Controls.Add(Me.FireDataSS)
        Me.Controls.Add(Me.GroupFireObject)
        Me.Name = "EditFireObject"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent
        Me.Text = "Define New Fire"
        CType(Me.FireDataSS, System.ComponentModel.ISupportInitialize).EndInit()
        Me.GroupFireObject.ResumeLayout(False)
        Me.GroupFireObject.PerformLayout()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents FireObjectsCancel As System.Windows.Forms.Button
    Friend WithEvents FireObjectsOK As System.Windows.Forms.Button
    Friend WithEvents FireObjectPlot As NPlot.Windows.PlotSurface2D
    Friend WithEvents FireName As System.Windows.Forms.TextBox
    Friend WithEvents Label9 As System.Windows.Forms.Label
    Friend WithEvents FireDataSS As C1.Win.C1FlexGrid.C1FlexGrid
    Friend WithEvents GroupFireObject As System.Windows.Forms.GroupBox
    Friend WithEvents FireCOYield As System.Windows.Forms.TextBox
    Friend WithEvents Label3 As System.Windows.Forms.Label
    Friend WithEvents FireSootYield As System.Windows.Forms.TextBox
    Friend WithEvents Label2 As System.Windows.Forms.Label
    Friend WithEvents FireCl As System.Windows.Forms.TextBox
    Friend WithEvents Label1 As System.Windows.Forms.Label
    Friend WithEvents FireMaterial As System.Windows.Forms.ComboBox
    Friend WithEvents Label84 As System.Windows.Forms.Label
    Friend WithEvents FireHoC As System.Windows.Forms.TextBox
    Friend WithEvents Label56 As System.Windows.Forms.Label
    Friend WithEvents FireN As System.Windows.Forms.TextBox
    Friend WithEvents FireH As System.Windows.Forms.TextBox
    Friend WithEvents Label64 As System.Windows.Forms.Label
    Friend WithEvents FireC As System.Windows.Forms.TextBox
    Friend WithEvents FireO As System.Windows.Forms.TextBox
    Friend WithEvents Label65 As System.Windows.Forms.Label
    Friend WithEvents Label39 As System.Windows.Forms.Label
    Friend WithEvents Label38 As System.Windows.Forms.Label
    Friend WithEvents Label59 As System.Windows.Forms.Label
    Friend WithEvents FireRadiativeFraction As System.Windows.Forms.TextBox
End Class
