import sys
from dataclasses import dataclass, field
from pathlib import Path

from PySide6.QtCore import Qt
from PySide6.QtGui import QAction
from PySide6.QtWidgets import (
    QApplication,
    QDockWidget,
    QFileDialog,
    QFrame,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QListWidget,
    QMainWindow,
    QMessageBox,
    QPushButton,
    QSizePolicy,
    QSplitter,
    QStatusBar,
    QTabWidget,
    QTableWidget,
    QTableWidgetItem,
    QToolBar,
    QVBoxLayout,
    QWidget,
)

from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure


@dataclass
class FireRampPoint:
    time: float
    hrr: float
    height: float = 0.0
    area: float = 0.3
    co_yield: float = 0.0
    soot_yield: float = 0.01
    hcn_yield: float = 0.0
    hcl_yield: float = 0.0
    trace_yield: float = 0.0


@dataclass
class CfastCase:
    title: str = "CEdit Qt Prototype Case"
    version: int = 7600

    simulation_time: float = 700.0
    print_interval: float = 1.0
    smokeview_interval: float = 10.0
    spreadsheet_interval: float = 1.0

    pressure: float = 101325.0
    relative_humidity: float = 50.0
    interior_temperature: float = 20.0
    exterior_temperature: float = 20.0

    comp_id: str = "Comp 1"
    comp_width: float = 5.0
    comp_depth: float = 5.0
    comp_height: float = 5.0
    comp_origin_x: float = 0.0
    comp_origin_y: float = 0.0
    comp_origin_z: float = 0.0
    comp_grid: tuple[int, int, int] = (50, 50, 50)

    wall_vent_id: str = "WallVent_1"
    wall_vent_bottom: float = 0.0
    wall_vent_height: float = 2.0
    wall_vent_width: float = 1.0
    wall_vent_face: str = "FRONT"
    wall_vent_offset: float = 2.0

    fire_id: str = "Initial Fire"
    fire_chem_id: str = "Initial Fire_Fire"
    fire_location_x: float = 2.5
    fire_location_y: float = 2.5

    carbon: int = 1
    chlorine: int = 0
    hydrogen: int = 4
    nitrogen: int = 0
    oxygen: int = 0
    heat_of_combustion: float = 50000.0
    radiative_fraction: float = 0.35

    fire_ramp: list[FireRampPoint] = field(default_factory=list)

    def sorted_fire_ramp(self) -> list[FireRampPoint]:
        return sorted(self.fire_ramp, key=lambda point: point.time)


def cfast_string(value: str) -> str:
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def cfast_number(value: float | int) -> str:
    if isinstance(value, int):
        return str(value)

    value = float(value)

    if abs(value - round(value)) < 1.0e-12:
        return str(int(round(value)))

    return f"{value:.6g}"


def cfast_vector(values) -> str:
    return ", ".join(cfast_number(value) for value in values)


def write_cfast_input(case: CfastCase, path: str | Path) -> None:
    ramp = case.sorted_fire_ramp()

    if not ramp:
        raise ValueError("Cannot export CFAST input because the fire ramp is empty.")

    for point in ramp:
        if point.time < 0.0:
            raise ValueError("Fire ramp times must be non-negative.")
        if point.hrr < 0.0:
            raise ValueError("Fire ramp HRR values must be non-negative.")

    path = Path(path)

    lines = []

    lines.append("!! CFAST input generated by CEdit Qt prototype")
    lines.append(
        f"&HEAD VERSION = {case.version}, TITLE = {cfast_string(case.title)} /"
    )
    lines.append("")

    lines.append(
        "&TIME "
        f"SIMULATION = {cfast_number(case.simulation_time)}, "
        f"PRINT = {cfast_number(case.print_interval)}, "
        f"SMOKEVIEW = {cfast_number(case.smokeview_interval)}, "
        f"SPREADSHEET = {cfast_number(case.spreadsheet_interval)} /"
    )

    lines.append(
        "&INIT "
        f"PRESSURE = {cfast_number(case.pressure)}, "
        f"RELATIVE_HUMIDITY = {cfast_number(case.relative_humidity)}, "
        f"INTERIOR_TEMPERATURE = {cfast_number(case.interior_temperature)}, "
        f"EXTERIOR_TEMPERATURE = {cfast_number(case.exterior_temperature)} /"
    )
    lines.append("")

    lines.append("!! Compartments")
    lines.append(
        f"&COMP ID = {cfast_string(case.comp_id)}, "
        f"DEPTH = {cfast_number(case.comp_depth)}, "
        f"HEIGHT = {cfast_number(case.comp_height)}, "
        f"WIDTH = {cfast_number(case.comp_width)}, "
        "CEILING_MATL_ID = 'OFF', "
        "WALL_MATL_ID = 'OFF', "
        "FLOOR_MATL_ID = 'OFF', "
        f"ORIGIN = {cfast_vector((case.comp_origin_x, case.comp_origin_y, case.comp_origin_z))}, "
        f"GRID = {cfast_vector(case.comp_grid)} /"
    )
    lines.append("")

    lines.append("!! Wall Vents")
    lines.append(
        f"&VENT TYPE = 'WALL', "
        f"ID = {cfast_string(case.wall_vent_id)}, "
        f"COMP_IDS = {cfast_string(case.comp_id)} 'OUTSIDE', "
        f"BOTTOM = {cfast_number(case.wall_vent_bottom)}, "
        f"HEIGHT = {cfast_number(case.wall_vent_height)}, "
        f"WIDTH = {cfast_number(case.wall_vent_width)}, "
        f"FACE = {cfast_string(case.wall_vent_face)}, "
        f"OFFSET = {cfast_number(case.wall_vent_offset)} /"
    )
    lines.append("")

    lines.append("!! Fires")
    lines.append(
        f"&FIRE ID = {cfast_string(case.fire_id)}, "
        f"COMP_ID = {cfast_string(case.comp_id)}, "
        f"FIRE_ID = {cfast_string(case.fire_chem_id)}, "
        f"LOCATION = {cfast_vector((case.fire_location_x, case.fire_location_y))} /"
    )

    lines.append(
        f"&CHEM ID = {cfast_string(case.fire_chem_id)}, "
        f"CARBON = {case.carbon}, "
        f"CHLORINE = {case.chlorine}, "
        f"HYDROGEN = {case.hydrogen}, "
        f"NITROGEN = {case.nitrogen}, "
        f"OXYGEN = {case.oxygen}, "
        f"HEAT_OF_COMBUSTION = {cfast_number(case.heat_of_combustion)}, "
        f"RADIATIVE_FRACTION = {cfast_number(case.radiative_fraction)} /"
    )

    lines.append(
        f"&TABL ID = {cfast_string(case.fire_chem_id)}, "
        "LABELS = 'TIME', 'HRR', 'HEIGHT', 'AREA', 'CO_YIELD', 'SOOT_YIELD', "
        "'HCN_YIELD', 'HCL_YIELD', 'TRACE_YIELD' /"
    )

    for point in ramp:
        data = (
            point.time,
            point.hrr,
            point.height,
            point.area,
            point.co_yield,
            point.soot_yield,
            point.hcn_yield,
            point.hcl_yield,
            point.trace_yield,
        )

        lines.append(
            f"&TABL ID = {cfast_string(case.fire_chem_id)}, "
            f"DATA = {cfast_vector(data)} /"
        )

    lines.append("")
    lines.append("&TAIL /")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


class RampPlotCanvas(FigureCanvas):
    def __init__(self, parent=None):
        self.figure = Figure(figsize=(5, 4), tight_layout=True)
        self.ax = self.figure.add_subplot(111)
        super().__init__(self.figure)
        self.setParent(parent)
        self.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        self.updateGeometry()

    def plot_ramp(self, points):
        self.ax.clear()

        if points:
            times = [p[0] for p in points]
            hrrs = [p[1] for p in points]
            self.ax.plot(times, hrrs, marker="o")
            self.ax.set_xlim(left=0.0)
            self.ax.set_ylim(bottom=0.0)
        else:
            self.ax.text(
                0.5,
                0.5,
                "Enter time / HRR points",
                ha="center",
                va="center",
                transform=self.ax.transAxes,
            )
            self.ax.set_xlim(0.0, 1.0)
            self.ax.set_ylim(0.0, 1.0)

        self.ax.set_title("HRR Ramp")
        self.ax.set_xlabel("Time (s)")
        self.ax.set_ylabel("HRR (kW)")
        self.ax.grid(True)
        self.draw()


class FiresTab(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.table = QTableWidget(8, 2)
        self.table.setHorizontalHeaderLabels(["Time (s)", "HRR (kW)"])
        self.table.horizontalHeader().setSectionResizeMode(
            QHeaderView.ResizeMode.Stretch
        )
        self.table.verticalHeader().setVisible(True)

        self.plot_canvas = RampPlotCanvas()

        self.info_label = QLabel(
            "Enter a fire ramp as time / HRR pairs.\n"
            "The plot updates whenever the table changes."
        )
        self.info_label.setFrameStyle(QFrame.Shape.StyledPanel | QFrame.Shadow.Sunken)

        add_row_button = QPushButton("Add Row")
        delete_row_button = QPushButton("Delete Selected")
        clear_button = QPushButton("Clear")

        add_row_button.clicked.connect(self.add_row)
        delete_row_button.clicked.connect(self.delete_selected_rows)
        clear_button.clicked.connect(self.clear_table)
        self.table.cellChanged.connect(self.update_plot)

        left_layout = QVBoxLayout()
        left_layout.addWidget(QLabel("<b>Fire Ramp Input</b>"))
        left_layout.addWidget(self.info_label)
        left_layout.addWidget(self.table)

        button_layout = QHBoxLayout()
        button_layout.addWidget(add_row_button)
        button_layout.addWidget(delete_row_button)
        button_layout.addWidget(clear_button)
        left_layout.addLayout(button_layout)

        left_widget = QWidget()
        left_widget.setLayout(left_layout)

        right_layout = QVBoxLayout()
        right_layout.addWidget(QLabel("<b>Ramp Preview</b>"))
        right_layout.addWidget(self.plot_canvas)

        right_widget = QWidget()
        right_widget.setLayout(right_layout)

        splitter = QSplitter(Qt.Orientation.Horizontal)
        splitter.addWidget(left_widget)
        splitter.addWidget(right_widget)
        splitter.setSizes([350, 650])

        main_layout = QVBoxLayout()
        main_layout.addWidget(splitter)
        self.setLayout(main_layout)

        self.load_demo_data()
        self.update_plot()

    def load_demo_data(self):
        demo_points = [
            (0, 0),
            (60, 250),
            (120, 750),
            (180, 1200),
            (240, 1200),
            (300, 600),
            (360, 0),
        ]

        self.table.blockSignals(True)
        self.table.setRowCount(max(8, len(demo_points)))

        for row, (time_val, hrr_val) in enumerate(demo_points):
            self.table.setItem(row, 0, QTableWidgetItem(str(time_val)))
            self.table.setItem(row, 1, QTableWidgetItem(str(hrr_val)))

        self.table.blockSignals(False)

    def add_row(self):
        self.table.insertRow(self.table.rowCount())

    def delete_selected_rows(self):
        selected_rows = sorted(
            {index.row() for index in self.table.selectionModel().selectedIndexes()},
            reverse=True,
        )

        for row in selected_rows:
            self.table.removeRow(row)

        if self.table.rowCount() == 0:
            self.table.setRowCount(1)

        self.update_plot()

    def clear_table(self):
        self.table.blockSignals(True)
        self.table.clearContents()
        self.table.blockSignals(False)
        self.update_plot()

    def extract_points(self):
        points = []

        for row in range(self.table.rowCount()):
            time_item = self.table.item(row, 0)
            hrr_item = self.table.item(row, 1)

            if time_item is None or hrr_item is None:
                continue

            time_text = time_item.text().strip()
            hrr_text = hrr_item.text().strip()

            if not time_text or not hrr_text:
                continue

            try:
                time_val = float(time_text)
                hrr_val = float(hrr_text)
            except ValueError:
                continue

            points.append((time_val, hrr_val))

        points.sort(key=lambda p: p[0])
        return points

    def update_plot(self):
        points = self.extract_points()
        self.plot_canvas.plot_ramp(points)


class PlaceholderTab(QWidget):
    def __init__(self, text, parent=None):
        super().__init__(parent)

        label = QLabel(text)
        label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        layout = QVBoxLayout()
        layout.addWidget(label)
        self.setLayout(layout)


class CeditMainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("Cedit Qt Prototype")
        self.resize(1200, 800)

        self.object_list = None
        self.tabs = None
        self.fires_tab = None

        self.build_menu()
        self.build_toolbar()
        self.build_dock()
        self.build_tabs()

        self.setStatusBar(QStatusBar(self))
        self.statusBar().showMessage("Ready")

    def build_menu(self):
        file_menu = self.menuBar().addMenu("&File")

        export_action = QAction("&Export CFAST Input...", self)
        export_action.triggered.connect(self.export_cfast_input)
        file_menu.addAction(export_action)

        file_menu.addSeparator()

        exit_action = QAction("E&xit", self)
        exit_action.triggered.connect(self.close)
        file_menu.addAction(exit_action)

        self.export_action = export_action
        self.exit_action = exit_action

    def build_toolbar(self):
        toolbar = QToolBar("Main Toolbar")
        self.addToolBar(toolbar)
        toolbar.addAction(self.export_action)
        toolbar.addAction(self.exit_action)

    def build_dock(self):
        project_dock = QDockWidget("Model Objects", self)
        project_dock.setAllowedAreas(
            Qt.DockWidgetArea.LeftDockWidgetArea
            | Qt.DockWidgetArea.RightDockWidgetArea
        )

        self.object_list = QListWidget()
        self.object_list.addItems(
            [
                "Model",
                "Compartments",
                "Vents",
                "Fires",
                "Targets",
                "Thermal Properties",
            ]
        )

        project_dock.setWidget(self.object_list)
        self.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, project_dock)

    def build_tabs(self):
        self.tabs = QTabWidget()
        self.fires_tab = FiresTab()

        self.tabs.addTab(PlaceholderTab("Model page coming soon"), "Model")
        self.tabs.addTab(PlaceholderTab("Compartments page coming soon"), "Compartments")
        self.tabs.addTab(PlaceholderTab("Vents page coming soon"), "Vents")
        self.tabs.addTab(self.fires_tab, "Fires")
        self.tabs.addTab(PlaceholderTab("Targets page coming soon"), "Targets")
        self.tabs.addTab(
            PlaceholderTab("Thermal Properties page coming soon"),
            "Thermal Properties",
        )

        self.setCentralWidget(self.tabs)

        self.object_list.currentRowChanged.connect(self.tabs.setCurrentIndex)
        self.tabs.currentChanged.connect(self.object_list.setCurrentRow)
        self.object_list.setCurrentRow(0)

    def build_cfast_case(self):
        points = self.fires_tab.extract_points()

        if not points:
            raise ValueError("Enter at least one valid time / HRR pair before exporting.")

        ramp = [
            FireRampPoint(time=time_val, hrr=hrr_val)
            for time_val, hrr_val in points
        ]

        last_time = max(time_val for time_val, _ in points)
        simulation_time = max(700.0, last_time + 60.0)

        return CfastCase(
            simulation_time=simulation_time,
            fire_ramp=ramp,
        )

    def export_cfast_input(self):
        path_text, _ = QFileDialog.getSaveFileName(
            self,
            "Export CFAST Input",
            "cedit_qt_test.in",
            "CFAST input files (*.in);;All files (*)",
        )

        if not path_text:
            return

        path = Path(path_text)

        try:
            case = self.build_cfast_case()
            write_cfast_input(case, path)
        except Exception as exc:
            QMessageBox.critical(self, "Export failed", str(exc))
            return

        self.statusBar().showMessage(f"Exported {path}", 5000)
        QMessageBox.information(self, "Export complete", f"Wrote:\n{path}")


def main():
    app = QApplication(sys.argv)
    app.setApplicationName("Cedit Qt Prototype")

    window = CeditMainWindow()
    window.show()

    sys.exit(app.exec())


if __name__ == "__main__":
    main()

