import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from PySide6.QtCore import Qt
from PySide6.QtGui import QAction
from PySide6.QtWidgets import (
    QApplication,
    QCheckBox,
    QFileDialog,
    QFrame,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMessageBox,
    QPushButton,
    QSizePolicy,
    QSpacerItem,
    QSplitter,
    QStatusBar,
    QTabWidget,
    QTableWidget,
    QTableWidgetItem,
    QTextEdit,
    QToolBar,
    QVBoxLayout,
    QWidget,
)

from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure


@dataclass
class FireRampPoint:
    time: float
    hrr: float
    height: float = 0.0
    area: float = 0.3
    co_yield: float = 0.0
    soot_yield: float = 0.01
    hcn_yield: float = 0.0
    hcl_yield: float = 0.0
    trace_yield: float = 0.0


@dataclass
class CfastCase:
    title: str = "CEdit Qt Prototype Case"
    version: int = 7600

    simulation_time: float = 3600.0
    print_interval: float = 60.0
    smokeview_interval: float = 60.0
    spreadsheet_interval: float = 60.0
    max_time_step: float | None = None

    pressure: float = 101325.0
    relative_humidity: float = 50.0
    interior_temperature: float = 20.0
    exterior_temperature: float = 20.0

    adiabatic_surfaces: bool = False
    lower_oxygen_limit: float = 0.1

    comp_id: str = "Comp 1"
    comp_width: float = 5.0
    comp_depth: float = 5.0
    comp_height: float = 5.0
    comp_origin_x: float = 0.0
    comp_origin_y: float = 0.0
    comp_origin_z: float = 0.0
    comp_grid: tuple[int, int, int] = (50, 50, 50)

    wall_vent_id: str = "WallVent_1"
    wall_vent_bottom: float = 0.0
    wall_vent_height: float = 2.0
    wall_vent_width: float = 1.0
    wall_vent_face: str = "FRONT"
    wall_vent_offset: float = 2.0

    fire_id: str = "Initial Fire"
    fire_chem_id: str = "Initial Fire_Fire"
    fire_location_x: float = 2.5
    fire_location_y: float = 2.5

    carbon: int = 1
    chlorine: int = 0
    hydrogen: int = 4
    nitrogen: int = 0
    oxygen: int = 0
    heat_of_combustion: float = 50000.0
    radiative_fraction: float = 0.35

    fire_ramp: list[FireRampPoint] = field(default_factory=list)

    def sorted_fire_ramp(self) -> list[FireRampPoint]:
        return sorted(self.fire_ramp, key=lambda point: point.time)


def cfast_string(value: str) -> str:
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def cfast_logical(value: bool) -> str:
    return ".TRUE." if value else ".FALSE."


def cfast_number(value: float | int) -> str:
    if isinstance(value, int):
        return str(value)

    value = float(value)

    if abs(value - round(value)) < 1.0e-12:
        return str(int(round(value)))

    return f"{value:.6g}"


def cfast_vector(values) -> str:
    return ", ".join(cfast_number(value) for value in values)


def parse_float(text: str, field_name: str, allow_default: bool = False) -> float | None:
    text = text.strip()

    if allow_default and text.lower() == "default":
        return None

    match = re.search(r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eEdD][-+]?\d+)?", text)

    if match is None:
        raise ValueError(f"Could not parse numeric value for {field_name}: {text!r}")

    return float(match.group(0).replace("D", "E").replace("d", "e"))


def add_wrapped_namelist(lines: list[str], name: str, fields: list[str]) -> None:
    max_len = 120
    indent = "      "

    current = f"&{name} "

    for index, field in enumerate(fields):
        suffix = "," if index < len(fields) - 1 else " /"
        entry = f"{field}{suffix}"

        if len(current) + len(entry) + 1 > max_len:
            lines.append(current.rstrip())
            current = indent + entry
        else:
            current = current + entry + " "

    lines.append(current.rstrip())


def write_cfast_input(case: CfastCase, path: str | Path) -> None:
    ramp = case.sorted_fire_ramp()

    if not ramp:
        raise ValueError("Cannot export CFAST input because the fire ramp is empty.")

    for point in ramp:
        if point.time < 0.0:
            raise ValueError("Fire ramp times must be non-negative.")
        if point.hrr < 0.0:
            raise ValueError("Fire ramp HRR values must be non-negative.")

    path = Path(path)
    lines: list[str] = []

    add_wrapped_namelist(
        lines,
        "HEAD",
        [
            f"VERSION = {case.version}",
            f"TITLE = {cfast_string(case.title)}",
        ],
    )

    lines.append("!! CFAST input generated by CEdit Qt prototype")
    lines.append("")

    add_wrapped_namelist(
        lines,
        "TIME",
        [
            f"SIMULATION = {cfast_number(case.simulation_time)}",
            f"PRINT = {cfast_number(case.print_interval)}",
            f"SMOKEVIEW = {cfast_number(case.smokeview_interval)}",
            f"SPREADSHEET = {cfast_number(case.spreadsheet_interval)}",
        ],
    )

    add_wrapped_namelist(
        lines,
        "INIT",
        [
            f"PRESSURE = {cfast_number(case.pressure)}",
            f"RELATIVE_HUMIDITY = {cfast_number(case.relative_humidity)}",
            f"INTERIOR_TEMPERATURE = {cfast_number(case.interior_temperature)}",
            f"EXTERIOR_TEMPERATURE = {cfast_number(case.exterior_temperature)}",
        ],
    )

    misc_fields = [
        f"ADIABATIC = {cfast_logical(case.adiabatic_surfaces)}",
        f"LOWER_OXYGEN_LIMIT = {cfast_number(case.lower_oxygen_limit)}",
        "OVERWRITE = .TRUE.",
    ]

    if case.max_time_step is not None:
        misc_fields.insert(1, f"MAX_TIME_STEP = {cfast_number(case.max_time_step)}")

    add_wrapped_namelist(lines, "MISC", misc_fields)
    lines.append("")

    lines.append("!! Compartments")
    add_wrapped_namelist(
        lines,
        "COMP",
        [
            f"ID = {cfast_string(case.comp_id)}",
            f"DEPTH = {cfast_number(case.comp_depth)}",
            f"HEIGHT = {cfast_number(case.comp_height)}",
            f"WIDTH = {cfast_number(case.comp_width)}",
            "CEILING_MATL_ID = 'OFF'",
            "WALL_MATL_ID = 'OFF'",
            "FLOOR_MATL_ID = 'OFF'",
            f"ORIGIN = {cfast_vector((case.comp_origin_x, case.comp_origin_y, case.comp_origin_z))}",
            f"GRID = {cfast_vector(case.comp_grid)}",
        ],
    )
    lines.append("")

    lines.append("!! Wall Vents")
    add_wrapped_namelist(
        lines,
        "VENT",
        [
            "TYPE = 'WALL'",
            f"ID = {cfast_string(case.wall_vent_id)}",
            f"COMP_IDS = {cfast_string(case.comp_id)} 'OUTSIDE'",
            f"BOTTOM = {cfast_number(case.wall_vent_bottom)}",
            f"HEIGHT = {cfast_number(case.wall_vent_height)}",
            f"WIDTH = {cfast_number(case.wall_vent_width)}",
            f"FACE = {cfast_string(case.wall_vent_face)}",
            f"OFFSET = {cfast_number(case.wall_vent_offset)}",
        ],
    )
    lines.append("")

    lines.append("!! Fires")
    add_wrapped_namelist(
        lines,
        "FIRE",
        [
            f"ID = {cfast_string(case.fire_id)}",
            f"COMP_ID = {cfast_string(case.comp_id)}",
            f"FIRE_ID = {cfast_string(case.fire_chem_id)}",
            f"LOCATION = {cfast_vector((case.fire_location_x, case.fire_location_y))}",
        ],
    )

    add_wrapped_namelist(
        lines,
        "CHEM",
        [
            f"ID = {cfast_string(case.fire_chem_id)}",
            f"CARBON = {case.carbon}",
            f"CHLORINE = {case.chlorine}",
            f"HYDROGEN = {case.hydrogen}",
            f"NITROGEN = {case.nitrogen}",
            f"OXYGEN = {case.oxygen}",
            f"HEAT_OF_COMBUSTION = {cfast_number(case.heat_of_combustion)}",
            f"RADIATIVE_FRACTION = {cfast_number(case.radiative_fraction)}",
        ],
    )

    lines.append(
        f"&TABL ID = {cfast_string(case.fire_chem_id)}, "
        "LABELS = 'TIME', 'HRR', 'HEIGHT', 'AREA', 'CO_YIELD',"
    )
    lines.append(
        "      'SOOT_YIELD', 'HCN_YIELD', 'HCL_YIELD', 'TRACE_YIELD' /"
    )

    for point in ramp:
        data = (
            point.time,
            point.hrr,
            point.height,
            point.area,
            point.co_yield,
            point.soot_yield,
            point.hcn_yield,
            point.hcl_yield,
            point.trace_yield,
        )

        add_wrapped_namelist(
            lines,
            "TABL",
            [
                f"ID = {cfast_string(case.fire_chem_id)}",
                f"DATA = {cfast_vector(data)}",
            ],
        )

    lines.append("")
    lines.append("&TAIL /")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


class SimulationTab(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.title_edit = QLineEdit("CEdit Qt Prototype Case")

        self.simulation_time_edit = QLineEdit("3600 s")
        self.print_interval_edit = QLineEdit("60 s")
        self.spreadsheet_interval_edit = QLineEdit("60 s")
        self.smokeview_interval_edit = QLineEdit("60 s")
        self.max_time_step_edit = QLineEdit("Default")

        self.interior_temperature_edit = QLineEdit("20 C")
        self.relative_humidity_edit = QLineEdit("50 %")
        self.exterior_temperature_edit = QLineEdit("20 C")
        self.pressure_edit = QLineEdit("101325 Pa")

        self.adiabatic_checkbox = QCheckBox("Adiabatic Compartment Surfaces")
        self.lower_oxygen_limit_edit = QLineEdit("0.1")

        self.message_panel = QTextEdit()
        self.message_panel.setReadOnly(True)
        self.message_panel.setPlainText("")
        self.message_panel.setMinimumHeight(140)

        self.build_layout()

    def build_layout(self):
        main_layout = QVBoxLayout()

        title_layout = QHBoxLayout()
        title_layout.addStretch(1)
        title_layout.addWidget(QLabel("Title:"))
        title_layout.addWidget(self.title_edit, 3)
        title_layout.addStretch(1)

        main_layout.addLayout(title_layout)

        middle_layout = QHBoxLayout()
        middle_layout.addStretch(1)
        middle_layout.addWidget(self.build_times_group())
        middle_layout.addSpacing(40)
        middle_layout.addWidget(self.build_conditions_group())
        middle_layout.addStretch(1)

        main_layout.addSpacing(15)
        main_layout.addLayout(middle_layout)
        main_layout.addSpacing(15)

        self.message_panel.setFrameStyle(QFrame.Shape.StyledPanel | QFrame.Shadow.Sunken)
        main_layout.addWidget(self.message_panel, 1)

        self.setLayout(main_layout)

    def build_times_group(self):
        group = QGroupBox("Simulation Times")
        layout = QGridLayout()

        labels_and_widgets = [
            ("Simulation Time:", self.simulation_time_edit),
            ("Text Output Interval:", self.print_interval_edit),
            ("Spreadsheet Output Interval:", self.spreadsheet_interval_edit),
            ("Smokeview Output Interval:", self.smokeview_interval_edit),
            ("Maximum Time Step:", self.max_time_step_edit),
        ]

        for row, (label, widget) in enumerate(labels_and_widgets):
            layout.addWidget(QLabel(label), row, 0, alignment=Qt.AlignmentFlag.AlignRight)
            layout.addWidget(widget, row, 1)

        layout.setColumnStretch(0, 1)
        layout.setColumnStretch(1, 1)
        group.setLayout(layout)
        group.setMinimumWidth(300)

        return group

    def build_conditions_group(self):
        group = QGroupBox("Simulation Conditions")
        outer_layout = QVBoxLayout()

        interior_group = QGroupBox("Interior")
        interior_layout = QGridLayout()
        interior_layout.addWidget(QLabel("Temperature:"), 0, 0)
        interior_layout.addWidget(self.interior_temperature_edit, 0, 1)
        interior_layout.addWidget(QLabel("Humidity:"), 0, 2)
        interior_layout.addWidget(self.relative_humidity_edit, 0, 3)
        interior_group.setLayout(interior_layout)

        exterior_group = QGroupBox("Exterior")
        exterior_layout = QGridLayout()
        exterior_layout.addWidget(QLabel("Temperature:"), 0, 0)
        exterior_layout.addWidget(self.exterior_temperature_edit, 0, 1)
        exterior_layout.addWidget(QLabel("Pressure:"), 0, 2)
        exterior_layout.addWidget(self.pressure_edit, 0, 3)
        exterior_group.setLayout(exterior_layout)

        misc_layout = QGridLayout()
        misc_layout.addWidget(self.adiabatic_checkbox, 0, 0, 1, 2)
        misc_layout.addWidget(QLabel("Lower Oxygen Limit:"), 1, 0)
        misc_layout.addWidget(self.lower_oxygen_limit_edit, 1, 1)

        outer_layout.addWidget(interior_group)
        outer_layout.addWidget(exterior_group)
        outer_layout.addLayout(misc_layout)

        group.setLayout(outer_layout)
        group.setMinimumWidth(380)

        return group

    def add_to_case(self, case: CfastCase):
        case.title = self.title_edit.text().strip() or "CFAST Simulation"

        case.simulation_time = parse_float(
            self.simulation_time_edit.text(),
            "Simulation Time",
        )
        case.print_interval = parse_float(
            self.print_interval_edit.text(),
            "Text Output Interval",
        )
        case.spreadsheet_interval = parse_float(
            self.spreadsheet_interval_edit.text(),
            "Spreadsheet Output Interval",
        )
        case.smokeview_interval = parse_float(
            self.smokeview_interval_edit.text(),
            "Smokeview Output Interval",
        )
        case.max_time_step = parse_float(
            self.max_time_step_edit.text(),
            "Maximum Time Step",
            allow_default=True,
        )

        case.interior_temperature = parse_float(
            self.interior_temperature_edit.text(),
            "Interior Temperature",
        )
        case.relative_humidity = parse_float(
            self.relative_humidity_edit.text(),
            "Humidity",
        )
        case.exterior_temperature = parse_float(
            self.exterior_temperature_edit.text(),
            "Exterior Temperature",
        )
        case.pressure = parse_float(
            self.pressure_edit.text(),
            "Pressure",
        )

        case.adiabatic_surfaces = self.adiabatic_checkbox.isChecked()
        case.lower_oxygen_limit = parse_float(
            self.lower_oxygen_limit_edit.text(),
            "Lower Oxygen Limit",
        )

    def set_message(self, text: str):
        self.message_panel.setPlainText(text)


class RampPlotCanvas(FigureCanvas):
    def __init__(self, parent=None):
        self.figure = Figure(figsize=(5, 4), tight_layout=True)
        self.ax = self.figure.add_subplot(111)
        super().__init__(self.figure)
        self.setParent(parent)
        self.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        self.updateGeometry()

    def plot_ramp(self, points):
        self.ax.clear()

        if points:
            times = [p[0] for p in points]
            hrrs = [p[1] for p in points]
            self.ax.plot(times, hrrs, marker="o")
            self.ax.set_xlim(left=0.0)
            self.ax.set_ylim(bottom=0.0)
        else:
            self.ax.text(
                0.5,
                0.5,
                "Enter time / HRR points",
                ha="center",
                va="center",
                transform=self.ax.transAxes,
            )
            self.ax.set_xlim(0.0, 1.0)
            self.ax.set_ylim(0.0, 1.0)

        self.ax.set_title("HRR Ramp")
        self.ax.set_xlabel("Time (s)")
        self.ax.set_ylabel("HRR (kW)")
        self.ax.grid(True)
        self.draw()


class FiresTab(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.table = QTableWidget(8, 2)
        self.table.setHorizontalHeaderLabels(["Time (s)", "HRR (kW)"])
        self.table.horizontalHeader().setSectionResizeMode(
            QHeaderView.ResizeMode.Stretch
        )
        self.table.verticalHeader().setVisible(True)

        self.plot_canvas = RampPlotCanvas()

        self.info_label = QLabel(
            "Enter a fire ramp as time / HRR pairs.\n"
            "The plot updates whenever the table changes."
        )
        self.info_label.setFrameStyle(QFrame.Shape.StyledPanel | QFrame.Shadow.Sunken)

        add_row_button = QPushButton("Add Row")
        delete_row_button = QPushButton("Delete Selected")
        clear_button = QPushButton("Clear")

        add_row_button.clicked.connect(self.add_row)
        delete_row_button.clicked.connect(self.delete_selected_rows)
        clear_button.clicked.connect(self.clear_table)
        self.table.cellChanged.connect(self.update_plot)

        left_layout = QVBoxLayout()
        left_layout.addWidget(QLabel("<b>Fire Ramp Input</b>"))
        left_layout.addWidget(self.info_label)
        left_layout.addWidget(self.table)

        button_layout = QHBoxLayout()
        button_layout.addWidget(add_row_button)
        button_layout.addWidget(delete_row_button)
        button_layout.addWidget(clear_button)
        left_layout.addLayout(button_layout)

        left_widget = QWidget()
        left_widget.setLayout(left_layout)

        right_layout = QVBoxLayout()
        right_layout.addWidget(QLabel("<b>Ramp Preview</b>"))
        right_layout.addWidget(self.plot_canvas)

        right_widget = QWidget()
        right_widget.setLayout(right_layout)

        splitter = QSplitter(Qt.Orientation.Horizontal)
        splitter.addWidget(left_widget)
        splitter.addWidget(right_widget)
        splitter.setSizes([350, 650])

        main_layout = QVBoxLayout()
        main_layout.addWidget(splitter)
        self.setLayout(main_layout)

        self.load_demo_data()
        self.update_plot()

    def load_demo_data(self):
        demo_points = [
            (0, 0),
            (60, 250),
            (120, 750),
            (180, 1200),
            (240, 1200),
            (300, 600),
            (360, 0),
        ]

        self.table.blockSignals(True)
        self.table.setRowCount(max(8, len(demo_points)))

        for row, (time_val, hrr_val) in enumerate(demo_points):
            self.table.setItem(row, 0, QTableWidgetItem(str(time_val)))
            self.table.setItem(row, 1, QTableWidgetItem(str(hrr_val)))

        self.table.blockSignals(False)

    def add_row(self):
        self.table.insertRow(self.table.rowCount())

    def delete_selected_rows(self):
        selected_rows = sorted(
            {index.row() for index in self.table.selectionModel().selectedIndexes()},
            reverse=True,
        )

        for row in selected_rows:
            self.table.removeRow(row)

        if self.table.rowCount() == 0:
            self.table.setRowCount(1)

        self.update_plot()

    def clear_table(self):
        self.table.blockSignals(True)
        self.table.clearContents()
        self.table.blockSignals(False)
        self.update_plot()

    def extract_points(self):
        points = []

        for row in range(self.table.rowCount()):
            time_item = self.table.item(row, 0)
            hrr_item = self.table.item(row, 1)

            if time_item is None or hrr_item is None:
                continue

            time_text = time_item.text().strip()
            hrr_text = hrr_item.text().strip()

            if not time_text or not hrr_text:
                continue

            try:
                time_val = float(time_text)
                hrr_val = float(hrr_text)
            except ValueError:
                continue

            points.append((time_val, hrr_val))

        points.sort(key=lambda p: p[0])
        return points

    def add_to_case(self, case: CfastCase):
        points = self.extract_points()

        if not points:
            raise ValueError("Enter at least one valid time / HRR pair before exporting.")

        case.fire_ramp = [
            FireRampPoint(time=time_val, hrr=hrr_val)
            for time_val, hrr_val in points
        ]

    def update_plot(self):
        points = self.extract_points()
        self.plot_canvas.plot_ramp(points)


class PlaceholderTab(QWidget):
    def __init__(self, text, parent=None):
        super().__init__(parent)

        label = QLabel(text)
        label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        layout = QVBoxLayout()
        layout.addWidget(label)
        self.setLayout(layout)


class CeditMainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("CEdit Qt Prototype")
        self.resize(1200, 800)

        self.current_path: Path | None = None

        self.simulation_tab = SimulationTab()
        self.fires_tab = FiresTab()
        self.tabs = None

        self.build_menu()
        self.build_toolbar()
        self.build_central_widget()

        self.setStatusBar(QStatusBar(self))
        self.statusBar().showMessage("No Errors")

    def build_menu(self):
        file_menu = self.menuBar().addMenu("&File")

        open_action = QAction("&Open...", self)
        open_action.triggered.connect(self.open_placeholder)
        file_menu.addAction(open_action)

        save_action = QAction("&Save", self)
        save_action.triggered.connect(self.save_cfast_input)
        file_menu.addAction(save_action)

        export_action = QAction("&Export CFAST Input...", self)
        export_action.triggered.connect(self.export_cfast_input)
        file_menu.addAction(export_action)

        file_menu.addSeparator()

        exit_action = QAction("E&xit", self)
        exit_action.triggered.connect(self.close)
        file_menu.addAction(exit_action)

        view_menu = self.menuBar().addMenu("&View")
        geometry_action = QAction("&Geometry", self)
        geometry_action.triggered.connect(self.geometry_placeholder)
        view_menu.addAction(geometry_action)

        results_action = QAction("&Results", self)
        results_action.triggered.connect(self.view_placeholder)
        view_menu.addAction(results_action)

        help_menu = self.menuBar().addMenu("&Help")
        about_action = QAction("&About CEdit Qt Prototype", self)
        about_action.triggered.connect(self.about)
        help_menu.addAction(about_action)

        self.open_action = open_action
        self.save_action = save_action
        self.export_action = export_action
        self.exit_action = exit_action
        self.geometry_action = geometry_action
        self.results_action = results_action

    def build_toolbar(self):
        toolbar = QToolBar("Main Toolbar")
        self.addToolBar(toolbar)
        toolbar.addAction(self.open_action)
        toolbar.addAction(self.save_action)
        toolbar.addAction(self.export_action)
        toolbar.addSeparator()
        toolbar.addAction(self.geometry_action)
        toolbar.addAction(self.results_action)
        toolbar.addSeparator()
        toolbar.addAction(self.exit_action)

    def build_central_widget(self):
        container = QWidget()
        layout = QVBoxLayout()

        self.tabs = QTabWidget()
        self.tabs.addTab(self.simulation_tab, "Simulation")
        self.tabs.addTab(
            PlaceholderTab("Thermal Properties page coming soon"),
            "Thermal Properties",
        )
        self.tabs.addTab(
            PlaceholderTab("Compartments page coming soon"),
            "Compartments",
        )
        self.tabs.addTab(
            PlaceholderTab("Wall Vents page coming soon"),
            "Wall Vents",
        )
        self.tabs.addTab(
            PlaceholderTab("Ceiling/Floor Vents page coming soon"),
            "Ceiling/Floor Vents",
        )
        self.tabs.addTab(
            PlaceholderTab("Mechanical Ventilation page coming soon"),
            "Mechanical Ventilation",
        )
        self.tabs.addTab(self.fires_tab, "Fires")
        self.tabs.addTab(PlaceholderTab("Targets page coming soon"), "Targets")
        self.tabs.addTab(
            PlaceholderTab("Detection / Suppression page coming soon"),
            "Detection / Suppression",
        )
        self.tabs.addTab(
            PlaceholderTab("Surface Connections page coming soon"),
            "Surface Connections",
        )
        self.tabs.addTab(PlaceholderTab("Output page coming soon"), "Output")

        layout.addWidget(self.tabs, 1)
        layout.addLayout(self.build_button_row())

        container.setLayout(layout)
        self.setCentralWidget(container)

    def build_button_row(self):
        row = QHBoxLayout()
        row.addStretch(1)

        open_button = QPushButton("Open")
        save_button = QPushButton("Save")
        geometry_button = QPushButton("Geometry")
        run_button = QPushButton("Run")
        view_button = QPushButton("View")

        open_button.clicked.connect(self.open_placeholder)
        save_button.clicked.connect(self.save_cfast_input)
        geometry_button.clicked.connect(self.geometry_placeholder)
        run_button.clicked.connect(self.run_placeholder)
        view_button.clicked.connect(self.view_placeholder)

        row.addWidget(open_button)
        row.addWidget(save_button)
        row.addItem(QSpacerItem(40, 1))
        row.addWidget(geometry_button)
        row.addWidget(run_button)
        row.addItem(QSpacerItem(40, 1))
        row.addWidget(view_button)
        row.addStretch(1)

        return row

    def build_cfast_case(self):
        case = CfastCase()
        self.simulation_tab.add_to_case(case)
        self.fires_tab.add_to_case(case)
        return case

    def save_cfast_input(self):
        if self.current_path is None:
            self.export_cfast_input()
            return

        self.write_case_to_path(self.current_path)

    def export_cfast_input(self):
        path_text, _ = QFileDialog.getSaveFileName(
            self,
            "Export CFAST Input",
            "cedit_qt_test.in",
            "CFAST input files (*.in);;All files (*)",
        )

        if not path_text:
            return

        path = Path(path_text)
        self.write_case_to_path(path)
        self.current_path = path

    def write_case_to_path(self, path: Path):
        try:
            case = self.build_cfast_case()
            write_cfast_input(case, path)
        except Exception as exc:
            self.simulation_tab.set_message(str(exc))
            self.statusBar().showMessage("Errors")
            QMessageBox.critical(self, "Export failed", str(exc))
            return

        message = f"Wrote CFAST input file:\n{path}"
        self.simulation_tab.set_message(message)
        self.statusBar().showMessage("No Errors")
        QMessageBox.information(self, "Export complete", message)

    def open_placeholder(self):
        QMessageBox.information(
            self,
            "Open",
            "Open existing CFAST input is not implemented yet.",
        )

    def geometry_placeholder(self):
        QMessageBox.information(
            self,
            "Geometry",
            "Geometry preview is not implemented yet.",
        )

    def run_placeholder(self):
        QMessageBox.information(
            self,
            "Run",
            "Running CFAST from CEdit Qt is not implemented yet.",
        )

    def view_placeholder(self):
        QMessageBox.information(
            self,
            "View",
            "Viewing results is not implemented yet.",
        )

    def about(self):
        QMessageBox.information(
            self,
            "About CEdit Qt Prototype",
            "Experimental Python/PySide6 prototype for a new CEdit front end.",
        )


def main():
    app = QApplication(sys.argv)
    app.setApplicationName("CEdit Qt Prototype")

    window = CeditMainWindow()
    window.show()

    sys.exit(app.exec())


if __name__ == "__main__":
    main()
