from pathlib import Path

from cfast_case import CfastCase


def cfast_string(value: str) -> str:
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def cfast_logical(value: bool) -> str:
    return ".TRUE." if value else ".FALSE."


def cfast_number(value: float | int) -> str:
    if isinstance(value, int):
        return str(value)

    value = float(value)

    if abs(value - round(value)) < 1.0e-12:
        return str(int(round(value)))

    return f"{value:.6g}"


def cfast_vector(values) -> str:
    return ", ".join(cfast_number(value) for value in values)


def cfast_string_vector(values) -> str:
    return ", ".join(cfast_string(value) for value in values)


def add_wrapped_namelist(lines: list[str], name: str, fields: list[str]) -> None:
    max_len = 120
    indent = "      "
    current = f"&{name} "

    for index, field in enumerate(fields):
        suffix = "," if index < len(fields) - 1 else " /"
        entry = f"{field}{suffix}"

        if len(current) + len(entry) + 1 > max_len:
            lines.append(current.rstrip())
            current = indent + entry
        else:
            current = current + entry + " "

    lines.append(current.rstrip())


def wall_vent_schedule(vent) -> tuple[list[float], list[float]]:
    t_values = list(vent.t_values)
    f_values = list(vent.f_values)

    if not t_values:
        if abs(vent.initial_open - 1.0) > 1.0e-12:
            return [0.0], [vent.initial_open]
        return [], []

    if abs(t_values[0]) > 1.0e-12:
        t_values.insert(0, 0.0)
        f_values.insert(0, vent.initial_open)

    return t_values, f_values


def validate_case(case: CfastCase) -> None:
    if not case.compartments:
        raise ValueError("At least one compartment is required.")

    compartment_ids = {compartment.id for compartment in case.compartments}

    for vent in case.wall_vents:
        if vent.first_comp_id not in compartment_ids:
            raise ValueError(
                f"Wall vent {vent.id!r}: first compartment "
                f"{vent.first_comp_id!r} does not exist."
            )

        if vent.second_comp_id != "OUTSIDE" and vent.second_comp_id not in compartment_ids:
            raise ValueError(
                f"Wall vent {vent.id!r}: second compartment "
                f"{vent.second_comp_id!r} does not exist."
            )

        if len(vent.t_values) != len(vent.f_values):
            raise ValueError(
                f"Wall vent {vent.id!r}: T and F schedules must have the same length."
            )


def write_cfast_input(case: CfastCase, path: str | Path) -> None:
    ramp = case.sorted_fire_ramp()

    if not ramp:
        raise ValueError("Cannot export CFAST input because the fire ramp is empty.")

    for point in ramp:
        if point.time < 0.0:
            raise ValueError("Fire ramp times must be non-negative.")
        if point.hrr < 0.0:
            raise ValueError("Fire ramp HRR values must be non-negative.")

    validate_case(case)

    path = Path(path)
    lines: list[str] = []

    add_wrapped_namelist(
        lines,
        "HEAD",
        [
            f"VERSION = {case.version}",
            f"TITLE = {cfast_string(case.title)}",
        ],
    )

    lines.append("!! CFAST input generated by CEdit Qt prototype")
    lines.append("")

    add_wrapped_namelist(
        lines,
        "TIME",
        [
            f"SIMULATION = {cfast_number(case.simulation_time)}",
            f"PRINT = {cfast_number(case.print_interval)}",
            f"SMOKEVIEW = {cfast_number(case.smokeview_interval)}",
            f"SPREADSHEET = {cfast_number(case.spreadsheet_interval)}",
        ],
    )

    add_wrapped_namelist(
        lines,
        "INIT",
        [
            f"PRESSURE = {cfast_number(case.pressure)}",
            f"RELATIVE_HUMIDITY = {cfast_number(case.relative_humidity)}",
            f"INTERIOR_TEMPERATURE = {cfast_number(case.interior_temperature)}",
            f"EXTERIOR_TEMPERATURE = {cfast_number(case.exterior_temperature)}",
        ],
    )

    misc_fields = [
        f"ADIABATIC = {cfast_logical(case.adiabatic_surfaces)}",
        f"LOWER_OXYGEN_LIMIT = {cfast_number(case.lower_oxygen_limit)}",
        "OVERWRITE = .TRUE.",
    ]

    if case.max_time_step is not None:
        misc_fields.insert(1, f"MAX_TIME_STEP = {cfast_number(case.max_time_step)}")

    add_wrapped_namelist(lines, "MISC", misc_fields)
    lines.append("")

    if case.materials:
        lines.append("!! Thermal Properties")

        for material in case.materials:
            fields = [
                f"ID = {cfast_string(material.id)}",
                f"MATERIAL = {cfast_string(material.material)}",
                f"CONDUCTIVITY = {cfast_number(material.conductivity)}",
                f"SPECIFIC_HEAT = {cfast_number(material.specific_heat)}",
                f"DENSITY = {cfast_number(material.density)}",
                f"THICKNESS = {cfast_number(material.thickness)}",
                f"EMISSIVITY = {cfast_number(material.emissivity)}",
            ]

            if material.fyi:
                fields.append(f"FYI = {cfast_string(material.fyi)}")

            add_wrapped_namelist(lines, "MATL", fields)

        lines.append("")

    lines.append("!! Compartments")

    for compartment in case.compartments:
        fields = [
            f"ID = {cfast_string(compartment.id)}",
            f"DEPTH = {cfast_number(compartment.depth)}",
            f"HEIGHT = {cfast_number(compartment.height)}",
            f"WIDTH = {cfast_number(compartment.width)}",
            f"ORIGIN = {cfast_vector((compartment.origin_x, compartment.origin_y, compartment.origin_z))}",
            f"GRID = {cfast_vector(compartment.grid)}",
            f"CEILING_MATL_ID = {cfast_string_vector(compartment.ceiling_matl_id)}",
            f"CEILING_THICKNESS = {cfast_vector(compartment.ceiling_thickness)}",
            f"WALL_MATL_ID = {cfast_string_vector(compartment.wall_matl_id)}",
            f"WALL_THICKNESS = {cfast_vector(compartment.wall_thickness)}",
            f"FLOOR_MATL_ID = {cfast_string_vector(compartment.floor_matl_id)}",
            f"FLOOR_THICKNESS = {cfast_vector(compartment.floor_thickness)}",
            f"HALL = {cfast_logical(compartment.hall)}",
            f"SHAFT = {cfast_logical(compartment.shaft)}",
            f"LEAK_AREA_RATIO = {cfast_vector((compartment.wall_leak_area_ratio, compartment.floor_leak_area_ratio))}",
            f"LEAK_AREA = {cfast_vector((compartment.wall_leak_area, compartment.floor_leak_area))}",
            f"FLOW_COEFFICIENT = {cfast_number(compartment.flow_coefficient)}",
        ]

        if compartment.cross_section_heights and compartment.cross_section_areas:
            fields.append(
                f"CROSS_SECT_HEIGHTS = {cfast_vector(compartment.cross_section_heights)}"
            )
            fields.append(
                f"CROSS_SECT_AREAS = {cfast_vector(compartment.cross_section_areas)}"
            )

        if compartment.fyi:
            fields.append(f"FYI = {cfast_string(compartment.fyi)}")

        add_wrapped_namelist(lines, "COMP", fields)

    lines.append("")

    if case.wall_vents:
        lines.append("!! Wall Vents")

        for vent in case.wall_vents:
            fields = [
                "TYPE = 'WALL'",
                f"ID = {cfast_string(vent.id)}",
                f"COMP_IDS = {cfast_string(vent.first_comp_id)} {cfast_string(vent.second_comp_id)}",
                f"BOTTOM = {cfast_number(vent.bottom)}",
                f"HEIGHT = {cfast_number(vent.height)}",
                f"WIDTH = {cfast_number(vent.width)}",
            ]

            t_values, f_values = wall_vent_schedule(vent)

            if t_values and f_values:
                fields.extend(
                    [
                        f"CRITERION = {cfast_string(vent.criterion)}",
                        f"T = {cfast_vector(t_values)}",
                        f"F = {cfast_vector(f_values)}",
                    ]
                )

            fields.extend(
                [
                    f"FACE = {cfast_string(vent.face)}",
                    f"OFFSET = {cfast_number(vent.offset)}",
                ]
            )

            if vent.fyi:
                fields.append(f"FYI = {cfast_string(vent.fyi)}")

            add_wrapped_namelist(lines, "VENT", fields)

        lines.append("")

    lines.append("!! Fires")
    add_wrapped_namelist(
        lines,
        "FIRE",
        [
            f"ID = {cfast_string(case.fire_id)}",
            f"COMP_ID = {cfast_string(case.comp_id)}",
            f"FIRE_ID = {cfast_string(case.fire_chem_id)}",
            f"LOCATION = {cfast_vector((case.fire_location_x, case.fire_location_y))}",
        ],
    )

    add_wrapped_namelist(
        lines,
        "CHEM",
        [
            f"ID = {cfast_string(case.fire_chem_id)}",
            f"CARBON = {case.carbon}",
            f"CHLORINE = {case.chlorine}",
            f"HYDROGEN = {case.hydrogen}",
            f"NITROGEN = {case.nitrogen}",
            f"OXYGEN = {case.oxygen}",
            f"HEAT_OF_COMBUSTION = {cfast_number(case.heat_of_combustion)}",
            f"RADIATIVE_FRACTION = {cfast_number(case.radiative_fraction)}",
        ],
    )

    lines.append(
        f"&TABL ID = {cfast_string(case.fire_chem_id)}, "
        "LABELS = 'TIME', 'HRR', 'HEIGHT', 'AREA', 'CO_YIELD',"
    )
    lines.append(
        "      'SOOT_YIELD', 'HCN_YIELD', 'HCL_YIELD', 'TRACE_YIELD' /"
    )

    for point in ramp:
        data = (
            point.time,
            point.hrr,
            point.height,
            point.area,
            point.co_yield,
            point.soot_yield,
            point.hcn_yield,
            point.hcl_yield,
            point.trace_yield,
        )

        add_wrapped_namelist(
            lines,
            "TABL",
            [
                f"ID = {cfast_string(case.fire_chem_id)}",
                f"DATA = {cfast_vector(data)}",
            ],
        )

    lines.append("")
    lines.append("&TAIL /")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
